/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Server.gltf -t -T -k -K s 
Files: Server.gltf [13.95KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\server\Server-transformed.glb [460.21KB] (-3199%)
Author: ipchilito (https://sketchfab.com/ipchilito)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/server-animado-22d2d048ce9749d4ae42e3af562f9bb5
Title: SERVER_ANIMADO
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    RACK_lambert4_0: THREE.Mesh
    RACK_lambert2_0: THREE.Mesh
    RACK_lambert3_0: THREE.Mesh
  }
  materials: {
    lambert4: THREE.MeshStandardMaterial
    lambert2: THREE.MeshStandardMaterial
    lambert3: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const Server: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/server/Server-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="RACK" position={[3.859, 62.945, 1.115]}>
            <mesh name="RACK_lambert4_0" geometry={nodes.RACK_lambert4_0.geometry} material={materials.lambert4} />
            <mesh name="RACK_lambert2_0" geometry={nodes.RACK_lambert2_0.geometry} material={materials.lambert2} />
            <mesh name="RACK_lambert3_0" geometry={nodes.RACK_lambert3_0.geometry} material={materials.lambert3} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/server/Server-transformed.glb');
export default Server;
