/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 SmilingEmojiTwo.gltf -t -T -k -K s 
Files: SmilingEmojiTwo.gltf [20.96KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\emoji-smile-two\SmilingEmojiTwo-transformed.glb [105.66KB] (-404%)
Author: JadeBarbiier (https://sketchfab.com/JadeBarbiier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emoji-smiling-2-da1d616bba83471e87da7364e3304287
Title: Emoji_Smiling_2
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['0']: THREE.Mesh
    ['1']: THREE.Mesh
    ['2']: THREE.Mesh
    ['3']: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Teeth: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const SmilingEmojiTwo: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/emoji-smile-two/SmilingEmojiTwo-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Awkward_005" scale={0.01}>
          <group name="group1" position={[-0.272, 0, 0]}>
            <group name="Awkward_005_Eyes_L2" position={[30.698, 6.679, 0.171]}>
              <mesh name="0" geometry={nodes['0'].geometry} material={materials.Brown} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
            </group>
            <group name="Head2">
              <mesh name="1" geometry={nodes['1'].geometry} material={materials.Skin} morphTargetDictionary={nodes['1'].morphTargetDictionary} morphTargetInfluences={nodes['1'].morphTargetInfluences} />
              <mesh name="2" geometry={nodes['2'].geometry} material={materials.Teeth} morphTargetDictionary={nodes['2'].morphTargetDictionary} morphTargetInfluences={nodes['2'].morphTargetInfluences} />
              <mesh name="3" geometry={nodes['3'].geometry} material={materials.Teeth} morphTargetDictionary={nodes['3'].morphTargetDictionary} morphTargetInfluences={nodes['3'].morphTargetInfluences} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/emoji-smile-two/SmilingEmojiTwo-transformed.glb')
export default SmilingEmojiTwo
