/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 SocialMediaIcons.gltf -t -T -k -K s 
Files: SocialMediaIcons.gltf [18.27KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\social-media-icons\all\SocialMediaIcons-transformed.glb [306.29KB] (-1576%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    V5_Icon1_V5_Icon1_0: THREE.Mesh
    V5_Icon2_V5_Icon2_0: THREE.Mesh
    V5_Icon3_V5_Icon3_0: THREE.Mesh
    V5_Icon4_V5_Icon4_0: THREE.Mesh
    V5_Icon5_V5_Icon5_0: THREE.Mesh
    V5_Icon6_V5_Icon6_0: THREE.Mesh
    V5_Icon7_V5_Icon7_0: THREE.Mesh
  }
  materials: {
    V5_Icon1: THREE.MeshStandardMaterial
    V5_Icon2: THREE.MeshStandardMaterial
    V5_Icon3: THREE.MeshStandardMaterial
    V5_Icon4: THREE.MeshStandardMaterial
    V5_Icon5: THREE.MeshStandardMaterial
    V5_Icon6: THREE.MeshStandardMaterial
    V5_Icon7: THREE.MeshStandardMaterial
  }
}

export default function SocialMediaIcons(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/social-media-icons/all/SocialMediaIcons-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        {/* <mesh name="V5_Icon1_V5_Icon1_0" geometry={nodes.V5_Icon1_V5_Icon1_0.geometry} material={materials.V5_Icon1} position={[-3.004, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="V5_Icon2_V5_Icon2_0" geometry={nodes.V5_Icon2_V5_Icon2_0.geometry} material={materials.V5_Icon2} position={[-2.012, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="V5_Icon3_V5_Icon3_0" geometry={nodes.V5_Icon3_V5_Icon3_0.geometry} material={materials.V5_Icon3} position={[-0.953, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="V5_Icon4_V5_Icon4_0" geometry={nodes.V5_Icon4_V5_Icon4_0.geometry} material={materials.V5_Icon4} position={[-0.007, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="V5_Icon5_V5_Icon5_0" geometry={nodes.V5_Icon5_V5_Icon5_0.geometry} material={materials.V5_Icon5} position={[0.884, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="V5_Icon6_V5_Icon6_0" geometry={nodes.V5_Icon6_V5_Icon6_0.geometry} material={materials.V5_Icon6} position={[1.848, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} /> */}
        <mesh name="V5_Icon7_V5_Icon7_0" geometry={nodes.V5_Icon7_V5_Icon7_0.geometry} material={materials.V5_Icon7} position={[2.833, 1.635, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/social-media-icons/all/SocialMediaIcons-transformed.glb')
