/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 RubiksCube.gltf -k -K -t -T s 
Files: RubiksCube.gltf [174.9KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\rubiks-cube\RubiksCube-transformed.glb [102.17KB] (42%)
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-rubiks-cube-3d-14bec82dd641417aa4b6a28d317ac18b
Title: ( FREE ) Rubik's cube 3D
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_9: THREE.Mesh
    Object_13: THREE.Mesh
    Object_18: THREE.Mesh
    Object_22: THREE.Mesh
    Object_25: THREE.Mesh
    Object_29: THREE.Mesh
    Object_34: THREE.Mesh
    Object_38: THREE.Mesh
    Object_43: THREE.Mesh
    Object_47: THREE.Mesh
    Object_50: THREE.Mesh
    Object_54: THREE.Mesh
    Object_59: THREE.Mesh
    Object_62: THREE.Mesh
    Object_66: THREE.Mesh
    Object_69: THREE.Mesh
    Object_73: THREE.Mesh
    Object_78: THREE.Mesh
    Object_82: THREE.Mesh
    Object_87: THREE.Mesh
    Object_91: THREE.Mesh
    Object_94: THREE.Mesh
    Object_98: THREE.Mesh
    Object_103: THREE.Mesh
    Object_107: THREE.Mesh
    Object_57: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/core-values/rubiks-cube/RubiksCube-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group);

  useFrame(()=> {
    if (actions.Animation) {
      actions.Animation.play()
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Cube_0" position={[3.993, 4, 0.007]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube001_1" position={[4.001, 2, -3.999]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube002_2" position={[4.008, 0, -0.008]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube003_3" position={[1.993, 4, 0.007]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube004_4" position={[4.001, 2, -1.999]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube005_5" position={[2.008, 0, -0.008]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube006_6" position={[-0.007, 3.979, -4.014]} rotation={[3.131, 0, Math.PI / 2]}>
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube007_7" position={[-0.001, -0.006, -2.014]} rotation={[-Math.PI, 0.011, 0]}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube008_8" position={[-0.007, 4.021, -0.014]} rotation={[3.131, 0, Math.PI / 2]}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube009_9" position={[-0.001, 3.994, -1.993]} rotation={[-Math.PI, -1.571, 0]}>
            <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube010_10" position={[1.999, 0.001, -2]} rotation={[0, -1.571, 0]}>
            <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube011_11" position={[3.999, 4.009, -2.008]} rotation={[-Math.PI, -1.571, 0]}>
            <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube012_12" position={[1.994, 1.994, -4]} rotation={[-Math.PI, 0, 0]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube014_14" position={[2.001, 2.001, 0]} rotation={[-Math.PI, 0, Math.PI / 2]}>
            <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube015_15" position={[0.001, 1.979, 0.001]} rotation={[1.573, -1.56, 0.002]}>
            <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube016_16" position={[1.999, 4.001, -2]} rotation={[0, 0.011, 0]}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube017_17" position={[4.001, 2.021, 0.001]} rotation={[1.573, -1.56, 0.002]}>
            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube018_18" position={[3.993, 4, -3.993]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube019_19" position={[0.001, 2, -3.999]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube020_20" position={[4.008, 0, -4.008]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube021_21" position={[1.993, 4, -3.993]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube022_22" position={[0.001, 2, -1.999]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube023_23" position={[2.008, 0, -4.008]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube024_24" position={[0.008, -0.021, -3.987]} rotation={[3.131, 0, Math.PI / 2]}>
            <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube025_25" position={[3.999, 0.009, -1.987]} rotation={[-Math.PI, 0.011, 0]}>
            <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Cube026_26" position={[0.008, 0.021, 0.013]} rotation={[3.131, 0, Math.PI / 2]}>
            <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.PaletteMaterial001} position={[2, 2, -2]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/rubiks-cube/RubiksCube-transformed.glb')
