/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 MoneyEffect.gltf -k -K -t -T s 
Files: MoneyEffect.gltf [655.73KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\money-effect\MoneyEffect-transformed.glb [580.36KB] (11%)
Author: vicente betoret ferrero (https://sketchfab.com/deathcow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/money-effect-1-73cfc2e353ca41b1b474c7c0137d8af3
Title: money effect "1"
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['Box008_Material_#37_0']: THREE.Mesh
    ['Box008_Material_#25_0']: THREE.Mesh
    ['Box008_Material_#30_0']: THREE.Mesh
    ['Box007_Material_#37_0']: THREE.Mesh
    ['Box007_Material_#25_0']: THREE.Mesh
    ['Box007_Material_#30_0']: THREE.Mesh
    ['Box009_Material_#37_0']: THREE.Mesh
    ['Box009_Material_#25_0']: THREE.Mesh
    ['Box009_Material_#30_0']: THREE.Mesh
    ['Box002_Material_#37_0']: THREE.Mesh
    ['Box002_Material_#25_0']: THREE.Mesh
    ['Box002_Material_#30_0']: THREE.Mesh
    ['Box005_Material_#37_0']: THREE.Mesh
    ['Box005_Material_#25_0']: THREE.Mesh
    ['Box005_Material_#30_0']: THREE.Mesh
    ['Box001_Material_#37_0']: THREE.Mesh
    ['Box001_Material_#25_0']: THREE.Mesh
    ['Box001_Material_#30_0']: THREE.Mesh
    ['Box011_Material_#37_0']: THREE.Mesh
    ['Box011_Material_#25_0']: THREE.Mesh
    ['Box011_Material_#30_0']: THREE.Mesh
    ['Box014_Material_#37_0']: THREE.Mesh
    ['Box014_Material_#25_0']: THREE.Mesh
    ['Box014_Material_#30_0']: THREE.Mesh
    ['Box004_Material_#37_0']: THREE.Mesh
    ['Box004_Material_#25_0']: THREE.Mesh
    ['Box004_Material_#30_0']: THREE.Mesh
    ['Box003_Material_#37_0']: THREE.Mesh
    ['Box003_Material_#25_0']: THREE.Mesh
    ['Box003_Material_#30_0']: THREE.Mesh
    ['Box006_Material_#37_0']: THREE.Mesh
    ['Box006_Material_#25_0']: THREE.Mesh
    ['Box006_Material_#30_0']: THREE.Mesh
    ['Box013_Material_#37_0']: THREE.Mesh
    ['Box013_Material_#25_0']: THREE.Mesh
    ['Box013_Material_#30_0']: THREE.Mesh
    ['Box010_Material_#37_0']: THREE.Mesh
    ['Box010_Material_#25_0']: THREE.Mesh
    ['Box010_Material_#30_0']: THREE.Mesh
    ['Box012_Material_#37_0']: THREE.Mesh
    ['Box012_Material_#25_0']: THREE.Mesh
    ['Box012_Material_#30_0']: THREE.Mesh
    ['Box015_Material_#37_0']: THREE.Mesh
    ['Box015_Material_#25_0']: THREE.Mesh
    ['Box015_Material_#30_0']: THREE.Mesh
    ['Box016_Material_#37_0']: THREE.Mesh
    ['Box016_Material_#25_0']: THREE.Mesh
    ['Box016_Material_#30_0']: THREE.Mesh
    ['Box017_Material_#37_0']: THREE.Mesh
    ['Box017_Material_#25_0']: THREE.Mesh
    ['Box017_Material_#30_0']: THREE.Mesh
    ['Box018_Material_#37_0']: THREE.Mesh
    ['Box018_Material_#25_0']: THREE.Mesh
    ['Box018_Material_#30_0']: THREE.Mesh
    ['Box019_Material_#37_0']: THREE.Mesh
    ['Box019_Material_#25_0']: THREE.Mesh
    ['Box019_Material_#30_0']: THREE.Mesh
    ['Box020_Material_#37_0']: THREE.Mesh
    ['Box020_Material_#25_0']: THREE.Mesh
    ['Box020_Material_#30_0']: THREE.Mesh
    ['Box021_Material_#37_0']: THREE.Mesh
    ['Box021_Material_#25_0']: THREE.Mesh
    ['Box021_Material_#30_0']: THREE.Mesh
    ['Box022_Material_#37_0']: THREE.Mesh
    ['Box022_Material_#25_0']: THREE.Mesh
    ['Box022_Material_#30_0']: THREE.Mesh
    ['Box023_Material_#37_0']: THREE.Mesh
    ['Box023_Material_#25_0']: THREE.Mesh
    ['Box023_Material_#30_0']: THREE.Mesh
    ['Box024_Material_#37_0']: THREE.Mesh
    ['Box024_Material_#25_0']: THREE.Mesh
    ['Box024_Material_#30_0']: THREE.Mesh
    ['Box025_Material_#37_0']: THREE.Mesh
    ['Box025_Material_#25_0']: THREE.Mesh
    ['Box025_Material_#30_0']: THREE.Mesh
    ['Box026_Material_#37_0']: THREE.Mesh
    ['Box026_Material_#25_0']: THREE.Mesh
    ['Box026_Material_#30_0']: THREE.Mesh
    ['Box027_Material_#37_0']: THREE.Mesh
    ['Box027_Material_#25_0']: THREE.Mesh
    ['Box027_Material_#30_0']: THREE.Mesh
    ['Box028_Material_#37_0']: THREE.Mesh
    ['Box028_Material_#25_0']: THREE.Mesh
    ['Box028_Material_#30_0']: THREE.Mesh
    ['Box029_Material_#37_0']: THREE.Mesh
    ['Box029_Material_#25_0']: THREE.Mesh
    ['Box029_Material_#30_0']: THREE.Mesh
    ['Box030_Material_#37_0']: THREE.Mesh
    ['Box030_Material_#25_0']: THREE.Mesh
    ['Box030_Material_#30_0']: THREE.Mesh
    ['Box031_Material_#37_0']: THREE.Mesh
    ['Box031_Material_#25_0']: THREE.Mesh
    ['Box031_Material_#30_0']: THREE.Mesh
    ['Box032_Material_#37_0']: THREE.Mesh
    ['Box032_Material_#25_0']: THREE.Mesh
    ['Box032_Material_#30_0']: THREE.Mesh
    ['Box033_Material_#37_0']: THREE.Mesh
    ['Box033_Material_#25_0']: THREE.Mesh
    ['Box033_Material_#30_0']: THREE.Mesh
    ['Box034_Material_#37_0']: THREE.Mesh
    ['Box034_Material_#25_0']: THREE.Mesh
    ['Box034_Material_#30_0']: THREE.Mesh
    ['Box035_Material_#37_0']: THREE.Mesh
    ['Box035_Material_#25_0']: THREE.Mesh
    ['Box035_Material_#30_0']: THREE.Mesh
    ['Box036_Material_#37_0']: THREE.Mesh
    ['Box036_Material_#25_0']: THREE.Mesh
    ['Box036_Material_#30_0']: THREE.Mesh
    ['Box037_Material_#37_0']: THREE.Mesh
    ['Box037_Material_#25_0']: THREE.Mesh
    ['Box037_Material_#30_0']: THREE.Mesh
    ['Box038_Material_#37_0']: THREE.Mesh
    ['Box038_Material_#25_0']: THREE.Mesh
    ['Box038_Material_#30_0']: THREE.Mesh
    ['Box039_Material_#37_0']: THREE.Mesh
    ['Box039_Material_#25_0']: THREE.Mesh
    ['Box039_Material_#30_0']: THREE.Mesh
    ['Box040_Material_#37_0']: THREE.Mesh
    ['Box040_Material_#25_0']: THREE.Mesh
    ['Box040_Material_#30_0']: THREE.Mesh
    ['Box041_Material_#37_0']: THREE.Mesh
    ['Box041_Material_#25_0']: THREE.Mesh
    ['Box041_Material_#30_0']: THREE.Mesh
    ['Box042_Material_#37_0']: THREE.Mesh
    ['Box042_Material_#25_0']: THREE.Mesh
    ['Box042_Material_#30_0']: THREE.Mesh
    ['Box043_Material_#37_0']: THREE.Mesh
    ['Box043_Material_#25_0']: THREE.Mesh
    ['Box043_Material_#30_0']: THREE.Mesh
    ['Box044_Material_#37_0']: THREE.Mesh
    ['Box044_Material_#25_0']: THREE.Mesh
    ['Box044_Material_#30_0']: THREE.Mesh
    ['Box045_Material_#37_0']: THREE.Mesh
    ['Box045_Material_#25_0']: THREE.Mesh
    ['Box045_Material_#30_0']: THREE.Mesh
    ['Box046_Material_#37_0']: THREE.Mesh
    ['Box046_Material_#25_0']: THREE.Mesh
    ['Box046_Material_#30_0']: THREE.Mesh
    ['Box047_Material_#37_0']: THREE.Mesh
    ['Box047_Material_#25_0']: THREE.Mesh
    ['Box047_Material_#30_0']: THREE.Mesh
    ['Box048_Material_#37_0']: THREE.Mesh
    ['Box048_Material_#25_0']: THREE.Mesh
    ['Box048_Material_#30_0']: THREE.Mesh
    ['Box049_Material_#37_0']: THREE.Mesh
    ['Box049_Material_#25_0']: THREE.Mesh
    ['Box049_Material_#30_0']: THREE.Mesh
    ['Box050_Material_#37_0']: THREE.Mesh
    ['Box050_Material_#25_0']: THREE.Mesh
    ['Box050_Material_#30_0']: THREE.Mesh
    ['Box051_Material_#37_0']: THREE.Mesh
    ['Box051_Material_#25_0']: THREE.Mesh
    ['Box051_Material_#30_0']: THREE.Mesh
    ['Box052_Material_#37_0']: THREE.Mesh
    ['Box052_Material_#25_0']: THREE.Mesh
    ['Box052_Material_#30_0']: THREE.Mesh
    ['Box053_Material_#37_0']: THREE.Mesh
    ['Box053_Material_#25_0']: THREE.Mesh
    ['Box053_Material_#30_0']: THREE.Mesh
    ['Box054_Material_#37_0']: THREE.Mesh
    ['Box054_Material_#25_0']: THREE.Mesh
    ['Box054_Material_#30_0']: THREE.Mesh
    ['Box055_Material_#37_0']: THREE.Mesh
    ['Box055_Material_#25_0']: THREE.Mesh
    ['Box055_Material_#30_0']: THREE.Mesh
    ['Box056_Material_#37_0']: THREE.Mesh
    ['Box056_Material_#25_0']: THREE.Mesh
    ['Box056_Material_#30_0']: THREE.Mesh
  }
  materials: {
    Material_37: THREE.MeshStandardMaterial
    Material_25: THREE.MeshStandardMaterial
    Material_30: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function MoneyEffect(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/money-effect/MoneyEffect-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Group001" position={[-0.018, 0.04, 1.471]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Box008" position={[48.532, 144.703, -3.099]} rotation={[-3.112, -0.829, 0.709]} scale={[0, -0.035, 0]}>
            <mesh name="Box008_Material_#37_0" geometry={nodes['Box008_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box008_Material_#25_0" geometry={nodes['Box008_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box008_Material_#30_0" geometry={nodes['Box008_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box007" position={[47.367, 142.4, -8.497]} rotation={[2.79, -0.262, 0.972]} scale={[0, -0.001, 0]}>
            <mesh name="Box007_Material_#37_0" geometry={nodes['Box007_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box007_Material_#25_0" geometry={nodes['Box007_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box007_Material_#30_0" geometry={nodes['Box007_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box009" position={[49.178, 147.088, 2.619]} rotation={[1.559, 1.307, -1.968]} scale={[0, -0.001, 0]}>
            <mesh name="Box009_Material_#37_0" geometry={nodes['Box009_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box009_Material_#25_0" geometry={nodes['Box009_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box009_Material_#30_0" geometry={nodes['Box009_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box002" position={[49.178, 147.088, 2.619]} rotation={[-1.063, -0.008, -0.015]} scale={[0, 0.035, 0]}>
            <mesh name="Box002_Material_#37_0" geometry={nodes['Box002_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box002_Material_#25_0" geometry={nodes['Box002_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box002_Material_#30_0" geometry={nodes['Box002_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box005" position={[39.417, 134.639, -25.067]} rotation={[1.388, 0.278, 1.441]} scale={[0, -0.035, 0]}>
            <mesh name="Box005_Material_#37_0" geometry={nodes['Box005_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box005_Material_#25_0" geometry={nodes['Box005_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box005_Material_#30_0" geometry={nodes['Box005_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box001" position={[49.181, 147.098, 2.641]} rotation={[Math.PI / 2, 1.306, -1.979]} scale={[0, -0.001, 0]}>
            <mesh name="Box001_Material_#37_0" geometry={nodes['Box001_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box001_Material_#25_0" geometry={nodes['Box001_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box001_Material_#30_0" geometry={nodes['Box001_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box011" position={[48.532, 144.703, -3.099]} rotation={[-1.063, -0.008, -0.015]} scale={[0, 0.035, 0]}>
            <mesh name="Box011_Material_#37_0" geometry={nodes['Box011_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box011_Material_#25_0" geometry={nodes['Box011_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box011_Material_#30_0" geometry={nodes['Box011_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box014" position={[49.181, 147.098, 2.641]} rotation={[-3.112, -0.829, 0.709]} scale={[0, -0.035, 0]}>
            <mesh name="Box014_Material_#37_0" geometry={nodes['Box014_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box014_Material_#25_0" geometry={nodes['Box014_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box014_Material_#30_0" geometry={nodes['Box014_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box004" position={[49.178, 147.088, 2.619]} rotation={[0.471, 0.591, 2.622]} scale={[0, -0.035, 0]}>
            <mesh name="Box004_Material_#37_0" geometry={nodes['Box004_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box004_Material_#25_0" geometry={nodes['Box004_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box004_Material_#30_0" geometry={nodes['Box004_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box003" position={[28.484, 128.135, -35.706]} rotation={[-0.307, 0.431, 2.189]} scale={[0, -0.002, 0]}>
            <mesh name="Box003_Material_#37_0" geometry={nodes['Box003_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box003_Material_#25_0" geometry={nodes['Box003_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box003_Material_#30_0" geometry={nodes['Box003_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box006" position={[-5.888, 112.472, -43.799]} rotation={[1.3, -0.423, 0.373]} scale={[0, -0.002, 0]}>
            <mesh name="Box006_Material_#37_0" geometry={nodes['Box006_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box006_Material_#25_0" geometry={nodes['Box006_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box006_Material_#30_0" geometry={nodes['Box006_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box013" position={[-16.582, 107.569, -40.855]} rotation={[0.753, -0.418, -0.9]} scale={[0, -0.002, 0]}>
            <mesh name="Box013_Material_#37_0" geometry={nodes['Box013_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box013_Material_#25_0" geometry={nodes['Box013_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box013_Material_#30_0" geometry={nodes['Box013_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box010" position={[-13.275, 109.127, -42.06]} rotation={[-1.518, 0.334, -3.054]} scale={[0, -0.001, 0]}>
            <mesh name="Box010_Material_#37_0" geometry={nodes['Box010_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box010_Material_#25_0" geometry={nodes['Box010_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box010_Material_#30_0" geometry={nodes['Box010_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box012" position={[-43.225, 89.066, -11.313]} rotation={[-2.068, -0.303, -2.582]} scale={[0, -0.001, 0]}>
            <mesh name="Box012_Material_#37_0" geometry={nodes['Box012_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box012_Material_#25_0" geometry={nodes['Box012_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box012_Material_#30_0" geometry={nodes['Box012_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
        </group>
        <group name="Group002" position={[0.07, 0.065, 1.462]} rotation={[-1.342, -1.052, 0.269]} scale={0.01}>
          <group name="Box015" position={[48.532, 144.703, -3.099]} rotation={[1.948, -0.345, -1.273]} scale={[0, -0.035, 0]}>
            <mesh name="Box015_Material_#37_0" geometry={nodes['Box015_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box015_Material_#25_0" geometry={nodes['Box015_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box015_Material_#30_0" geometry={nodes['Box015_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box016" position={[47.367, 142.4, -8.497]} rotation={[2.705, -0.298, -0.878]} scale={[0, -0.001, 0]}>
            <mesh name="Box016_Material_#37_0" geometry={nodes['Box016_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box016_Material_#25_0" geometry={nodes['Box016_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box016_Material_#30_0" geometry={nodes['Box016_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box017" position={[49.178, 147.088, 2.619]} rotation={[-1.987, 0.228, 1.676]} scale={[0, -0.001, 0]}>
            <mesh name="Box017_Material_#37_0" geometry={nodes['Box017_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box017_Material_#25_0" geometry={nodes['Box017_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box017_Material_#30_0" geometry={nodes['Box017_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box018" position={[49.178, 147.088, 2.619]} rotation={[-2.475, 0.014, -0.011]} scale={[0, 0.035, 0]}>
            <mesh name="Box018_Material_#37_0" geometry={nodes['Box018_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box018_Material_#25_0" geometry={nodes['Box018_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box018_Material_#30_0" geometry={nodes['Box018_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box019" position={[39.417, 134.639, -25.067]} rotation={[-2.602, 0.598, -0.357]} scale={[0, -0.035, 0]}>
            <mesh name="Box019_Material_#37_0" geometry={nodes['Box019_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box019_Material_#25_0" geometry={nodes['Box019_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box019_Material_#30_0" geometry={nodes['Box019_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box020" position={[49.181, 147.098, 2.641]} rotation={[-1.99, 0.227, 1.677]} scale={[0, -0.001, 0]}>
            <mesh name="Box020_Material_#37_0" geometry={nodes['Box020_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box020_Material_#25_0" geometry={nodes['Box020_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box020_Material_#30_0" geometry={nodes['Box020_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box021" position={[48.532, 144.703, -3.099]} rotation={[-2.475, 0.014, -0.011]} scale={[0, 0.035, 0]}>
            <mesh name="Box021_Material_#37_0" geometry={nodes['Box021_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box021_Material_#25_0" geometry={nodes['Box021_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box021_Material_#30_0" geometry={nodes['Box021_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box022" position={[49.181, 147.098, 2.641]} rotation={[1.948, -0.345, -1.273]} scale={[0, -0.035, 0]}>
            <mesh name="Box022_Material_#37_0" geometry={nodes['Box022_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box022_Material_#25_0" geometry={nodes['Box022_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box022_Material_#30_0" geometry={nodes['Box022_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box023" position={[49.178, 147.088, 2.619]} rotation={[-1.165, 0.752, -1.403]} scale={[0, -0.035, 0]}>
            <mesh name="Box023_Material_#37_0" geometry={nodes['Box023_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box023_Material_#25_0" geometry={nodes['Box023_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box023_Material_#30_0" geometry={nodes['Box023_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box024" position={[28.484, 128.135, -35.706]} rotation={[0.042, 1.027, -2.772]} scale={[0, -0.002, 0]}>
            <mesh name="Box024_Material_#37_0" geometry={nodes['Box024_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box024_Material_#25_0" geometry={nodes['Box024_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box024_Material_#30_0" geometry={nodes['Box024_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box025" position={[-5.888, 112.472, -43.799]} rotation={[1.707, -0.468, 0.12]} scale={[0, -0.002, 0]}>
            <mesh name="Box025_Material_#37_0" geometry={nodes['Box025_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box025_Material_#25_0" geometry={nodes['Box025_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box025_Material_#30_0" geometry={nodes['Box025_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box026" position={[-16.582, 107.569, -40.855]} rotation={[1.032, -0.44, -1.192]} scale={[0, -0.002, 0]}>
            <mesh name="Box026_Material_#37_0" geometry={nodes['Box026_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box026_Material_#25_0" geometry={nodes['Box026_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box026_Material_#30_0" geometry={nodes['Box026_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box027" position={[-13.275, 109.127, -42.06]} rotation={[-1.144, 0.504, -2.871]} scale={[0, -0.001, 0]}>
            <mesh name="Box027_Material_#37_0" geometry={nodes['Box027_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box027_Material_#25_0" geometry={nodes['Box027_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box027_Material_#30_0" geometry={nodes['Box027_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box028" position={[-43.225, 89.066, -11.313]} rotation={[-1.804, 0.254, -2.016]} scale={[0, -0.001, 0]}>
            <mesh name="Box028_Material_#37_0" geometry={nodes['Box028_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box028_Material_#25_0" geometry={nodes['Box028_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box028_Material_#30_0" geometry={nodes['Box028_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Helix002" position={[-0.516, 147.098, 2.641]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <group name="Group003" position={[0.023, 0.057, 1.471]} rotation={[-Math.PI / 2, -0.793, 0]} scale={0.01}>
          <group name="Box029" position={[48.532, 144.703, -3.099]} rotation={[1.982, -0.464, -1.142]} scale={[0, -0.035, 0]}>
            <mesh name="Box029_Material_#37_0" geometry={nodes['Box029_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box029_Material_#25_0" geometry={nodes['Box029_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box029_Material_#30_0" geometry={nodes['Box029_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box030" position={[49.178, 147.088, 2.619]} rotation={[-2.006, 0.397, 1.682]} scale={[0, -0.001, 0]}>
            <mesh name="Box030_Material_#37_0" geometry={nodes['Box030_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box030_Material_#25_0" geometry={nodes['Box030_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box030_Material_#30_0" geometry={nodes['Box030_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box031" position={[48.532, 144.703, -3.099]} rotation={[-2.407, 0.013, -0.012]} scale={[0, 0.035, 0]}>
            <mesh name="Box031_Material_#37_0" geometry={nodes['Box031_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box031_Material_#25_0" geometry={nodes['Box031_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box031_Material_#30_0" geometry={nodes['Box031_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box032" position={[-43.225, 89.066, -11.313]} rotation={[-1.824, 0.158, -2.097]} scale={[0, -0.001, 0]}>
            <mesh name="Box032_Material_#37_0" geometry={nodes['Box032_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box032_Material_#25_0" geometry={nodes['Box032_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box032_Material_#30_0" geometry={nodes['Box032_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box033" position={[49.181, 147.098, 2.641]} rotation={[1.982, -0.464, -1.142]} scale={[0, -0.035, 0]}>
            <mesh name="Box033_Material_#37_0" geometry={nodes['Box033_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box033_Material_#25_0" geometry={nodes['Box033_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box033_Material_#30_0" geometry={nodes['Box033_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box034" position={[-16.582, 107.569, -40.855]} rotation={[0.949, -0.426, -1.105]} scale={[0, -0.002, 0]}>
            <mesh name="Box034_Material_#37_0" geometry={nodes['Box034_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box034_Material_#25_0" geometry={nodes['Box034_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box034_Material_#30_0" geometry={nodes['Box034_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box035" position={[47.367, 142.4, -8.497]} rotation={[2.717, -0.303, -0.653]} scale={[0, -0.001, 0]}>
            <mesh name="Box035_Material_#37_0" geometry={nodes['Box035_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box035_Material_#25_0" geometry={nodes['Box035_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box035_Material_#30_0" geometry={nodes['Box035_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box036" position={[49.178, 147.088, 2.619]} rotation={[-2.407, 0.013, -0.012]} scale={[0, 0.035, 0]}>
            <mesh name="Box036_Material_#37_0" geometry={nodes['Box036_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box036_Material_#25_0" geometry={nodes['Box036_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box036_Material_#30_0" geometry={nodes['Box036_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box037" position={[-13.275, 109.127, -42.06]} rotation={[-1.267, 0.441, -2.925]} scale={[0, -0.001, 0]}>
            <mesh name="Box037_Material_#37_0" geometry={nodes['Box037_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box037_Material_#25_0" geometry={nodes['Box037_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box037_Material_#30_0" geometry={nodes['Box037_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box038" position={[39.417, 134.639, -25.067]} rotation={[-3.055, 0.858, -0.01]} scale={[0, -0.035, 0]}>
            <mesh name="Box038_Material_#37_0" geometry={nodes['Box038_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box038_Material_#25_0" geometry={nodes['Box038_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box038_Material_#30_0" geometry={nodes['Box038_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box039" position={[49.181, 147.098, 2.641]} rotation={[-2.01, 0.396, 1.683]} scale={[0, -0.001, 0]}>
            <mesh name="Box039_Material_#37_0" geometry={nodes['Box039_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box039_Material_#25_0" geometry={nodes['Box039_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box039_Material_#30_0" geometry={nodes['Box039_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box040" position={[28.484, 128.135, -35.706]} rotation={[0.018, 0.747, 2.924]} scale={[0, -0.002, 0]}>
            <mesh name="Box040_Material_#37_0" geometry={nodes['Box040_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box040_Material_#25_0" geometry={nodes['Box040_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box040_Material_#30_0" geometry={nodes['Box040_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box041" position={[-5.888, 112.472, -43.799]} rotation={[1.559, -0.441, 0.211]} scale={[0, -0.002, 0]}>
            <mesh name="Box041_Material_#37_0" geometry={nodes['Box041_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box041_Material_#25_0" geometry={nodes['Box041_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box041_Material_#30_0" geometry={nodes['Box041_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box042" position={[49.178, 147.088, 2.619]} rotation={[-1.048, 0.863, -1.588]} scale={[0, -0.035, 0]}>
            <mesh name="Box042_Material_#37_0" geometry={nodes['Box042_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box042_Material_#25_0" geometry={nodes['Box042_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box042_Material_#30_0" geometry={nodes['Box042_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
        </group>
        <group name="Group004" position={[0.066, 0.137, 1.462]} rotation={[1.189, -1.264, 2.846]} scale={0.01}>
          <group name="Box043" position={[49.178, 147.088, 2.619]} rotation={[-1.961, -0.016, 1.674]} scale={[0, -0.001, 0]}>
            <mesh name="Box043_Material_#37_0" geometry={nodes['Box043_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box043_Material_#25_0" geometry={nodes['Box043_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box043_Material_#30_0" geometry={nodes['Box043_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box044" position={[39.417, 134.639, -25.067]} rotation={[-2.308, 0.255, -0.522]} scale={[0, -0.035, 0]}>
            <mesh name="Box044_Material_#37_0" geometry={nodes['Box044_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box044_Material_#25_0" geometry={nodes['Box044_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box044_Material_#30_0" geometry={nodes['Box044_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box045" position={[48.532, 144.703, -3.099]} rotation={[1.929, -0.168, -1.447]} scale={[0, -0.035, 0]}>
            <mesh name="Box045_Material_#37_0" geometry={nodes['Box045_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box045_Material_#25_0" geometry={nodes['Box045_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box045_Material_#30_0" geometry={nodes['Box045_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box046" position={[49.181, 147.098, 2.641]} rotation={[-1.964, -0.017, 1.675]} scale={[0, -0.001, 0]}>
            <mesh name="Box046_Material_#37_0" geometry={nodes['Box046_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box046_Material_#25_0" geometry={nodes['Box046_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box046_Material_#30_0" geometry={nodes['Box046_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box047" position={[-5.888, 112.472, -43.799]} rotation={[2.722, -0.898, -0.304]} scale={[0, -0.002, 0]}>
            <mesh name="Box047_Material_#37_0" geometry={nodes['Box047_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box047_Material_#25_0" geometry={nodes['Box047_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box047_Material_#30_0" geometry={nodes['Box047_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box048" position={[-16.582, 107.569, -40.855]} rotation={[1.56, -0.696, -1.753]} scale={[0, -0.002, 0]}>
            <mesh name="Box048_Material_#37_0" geometry={nodes['Box048_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box048_Material_#25_0" geometry={nodes['Box048_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box048_Material_#30_0" geometry={nodes['Box048_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box049" position={[-13.275, 109.127, -42.06]} rotation={[-0.099, 1.043, -2.82]} scale={[0, -0.001, 0]}>
            <mesh name="Box049_Material_#37_0" geometry={nodes['Box049_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box049_Material_#25_0" geometry={nodes['Box049_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box049_Material_#30_0" geometry={nodes['Box049_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box050" position={[28.484, 128.135, -35.706]} rotation={[-0.589, 1.247, -1.46]} scale={[0, -0.002, 0]}>
            <mesh name="Box050_Material_#37_0" geometry={nodes['Box050_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box050_Material_#25_0" geometry={nodes['Box050_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box050_Material_#30_0" geometry={nodes['Box050_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box051" position={[-43.225, 89.066, -11.313]} rotation={[-1.796, 0.592, -1.721]} scale={[0, -0.001, 0]}>
            <mesh name="Box051_Material_#37_0" geometry={nodes['Box051_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box051_Material_#25_0" geometry={nodes['Box051_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box051_Material_#30_0" geometry={nodes['Box051_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box052" position={[49.181, 147.098, 2.641]} rotation={[1.929, -0.168, -1.447]} scale={[0, -0.035, 0]}>
            <mesh name="Box052_Material_#37_0" geometry={nodes['Box052_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box052_Material_#25_0" geometry={nodes['Box052_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box052_Material_#30_0" geometry={nodes['Box052_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box053" position={[47.367, 142.4, -8.497]} rotation={[2.692, -0.288, -1.163]} scale={[0, -0.001, 0]}>
            <mesh name="Box053_Material_#37_0" geometry={nodes['Box053_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box053_Material_#25_0" geometry={nodes['Box053_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box053_Material_#30_0" geometry={nodes['Box053_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box054" position={[48.532, 144.703, -3.099]} rotation={[-2.556, 0.015, -0.01]} scale={[0, 0.035, 0]}>
            <mesh name="Box054_Material_#37_0" geometry={nodes['Box054_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box054_Material_#25_0" geometry={nodes['Box054_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box054_Material_#30_0" geometry={nodes['Box054_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box055" position={[49.178, 147.088, 2.619]} rotation={[-2.556, 0.015, -0.01]} scale={[0, 0.035, 0]}>
            <mesh name="Box055_Material_#37_0" geometry={nodes['Box055_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box055_Material_#25_0" geometry={nodes['Box055_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box055_Material_#30_0" geometry={nodes['Box055_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Box056" position={[49.178, 147.088, 2.619]} rotation={[-1.269, 0.572, -1.192]} scale={[0, -0.035, 0]}>
            <mesh name="Box056_Material_#37_0" geometry={nodes['Box056_Material_#37_0'].geometry} material={materials.Material_37} />
            <mesh name="Box056_Material_#25_0" geometry={nodes['Box056_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh name="Box056_Material_#30_0" geometry={nodes['Box056_Material_#30_0'].geometry} material={materials.Material_30} />
          </group>
          <group name="Helix004" position={[-0.516, 147.098, 2.641]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/money-effect/MoneyEffect-transformed.glb')
