/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MarbleColumn.gltf -k -K -t -T s 
Files: MarbleColumn.gltf [5.9KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\marble-column\MarbleColumn-transformed.glb [498.91KB] (-8356%)
Author: Christian S (https://sketchfab.com/ChristianSX)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/marble-column-free-asset-free-low-poly-3d-model-18e018890b72444c9eda17a5eaa166b4
Title: Marble Column Free Asset Free low-poly 3D model
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Small_Column_Column_0: THREE.Mesh
  }
  materials: {
    Column: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/core-values/marble-column/MarbleColumn-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Small_Column_Column_0" geometry={nodes.Small_Column_Column_0.geometry} material={materials.Column} position={[0, 0.582, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/marble-column/MarbleColumn-transformed.glb')
