/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 BankVault.gltf -t -T -k -K --shadows 
Files: BankVault.gltf [45.31KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\bank-vault\BankVault-transformed.glb [951.07KB] (-1999%)
Author: comphonia (https://sketchfab.com/comphonia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bank-vault-af389a721faa4ec49eaec7ec2a215371
Title: Bank Vault
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_oxidizedMetal_0: THREE.Mesh
    Cylinder002_oxidizedMetal_0: THREE.Mesh
    VaultDoor_oxidizedMetal_0: THREE.Mesh
    VaultDoor_VaultDoor_0: THREE.Mesh
    Vault_oxidizedMetal_0: THREE.Mesh
    Object004_VaultJamb_0: THREE.Mesh
    ShortStackBent036_100Dollar_0: THREE.Mesh
    Plane001_metalDiamondGrid_0: THREE.Mesh
  }
  materials: {
    oxidizedMetal: THREE.MeshStandardMaterial
    VaultDoor: THREE.MeshStandardMaterial
    VaultJamb: THREE.MeshStandardMaterial
    ['100Dollar']: THREE.MeshStandardMaterial
    metalDiamondGrid: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function BankVault(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/bank-vault/BankVault-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group);

 

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="VaultDoor" position={[4256.487, 177.217, 194.891]}>
            <group name="Cylinder001" position={[125.441, -57.326, 31.5]} rotation={[0, 0, 1.719]}>
              <mesh name="Cylinder001_oxidizedMetal_0" castShadow receiveShadow geometry={nodes.Cylinder001_oxidizedMetal_0.geometry} material={materials.oxidizedMetal} />
            </group>
            <group name="Cylinder002" position={[202.68, -57.326, 13.544]} rotation={[0, 0, 1.719]} >
              <mesh name="Cylinder002_oxidizedMetal_0" castShadow receiveShadow geometry={nodes.Cylinder002_oxidizedMetal_0.geometry} material={materials.oxidizedMetal} />
            </group>
            <group name="Object_11" position={[78.946, -71.652, 9.678]}>
              <mesh name="VaultDoor_oxidizedMetal_0" castShadow receiveShadow geometry={nodes.VaultDoor_oxidizedMetal_0.geometry} material={materials.oxidizedMetal} />
              <mesh name="VaultDoor_VaultDoor_0" castShadow receiveShadow geometry={nodes.VaultDoor_VaultDoor_0.geometry} material={materials.VaultDoor} />
            </group>
          </group>
        </group>
        <mesh name="Vault_oxidizedMetal_0" castShadow receiveShadow geometry={nodes.Vault_oxidizedMetal_0.geometry} material={materials.oxidizedMetal} position={[4047.975, -0.395, 769.855]} rotation={[-Math.PI / 2, 0, 0]} scale={0.697} />
        <mesh name="Object004_VaultJamb_0" castShadow receiveShadow geometry={nodes.Object004_VaultJamb_0.geometry} material={materials.VaultJamb} position={[4092.475, 120.544, 154.167]} scale={0.982} />
        <mesh name="ShortStackBent036_100Dollar_0" castShadow receiveShadow geometry={nodes.ShortStackBent036_100Dollar_0.geometry} material={materials['100Dollar']} position={[4249.568, 16.735, 73.99]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Plane001_metalDiamondGrid_0" castShadow receiveShadow geometry={nodes.Plane001_metalDiamondGrid_0.geometry} material={materials.metalDiamondGrid} position={[4374.049, 0, 4.385]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/bank-vault/BankVault-transformed.glb')
