'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -k -K -t -T s 
Files: scene.gltf [157.88KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\digital-solutions\ghost-in-shell\scene-transformed.glb [1.39MB] (-780%)
Author: PolyBoi (https://sketchfab.com/nikars)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-in-the-shell-cyborg-head-7a3ad0a509a746b5acaf206d638a2d8a
Title: Ghost in the Shell Cyborg Head
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    SideRot001_low_Head_0: THREE.Mesh
    SideRot002_low_Head_0: THREE.Mesh
    SideRot003_low_Head_0: THREE.Mesh
    SideRot004_lowRight_Head_0: THREE.Mesh
    sideRight_low_Head_0: THREE.Mesh
    SideRot004_low_Head_0: THREE.Mesh
    side_low_Head_0: THREE.Mesh
    SideRot001_lowRight_Head_0: THREE.Mesh
    SideRot002_lowRight_Head_0: THREE.Mesh
    SideRot003_lowRight_Head_0: THREE.Mesh
    TopRot002_low_Head_0: THREE.Mesh
    TopRot_low_Head_0: THREE.Mesh
    TopInner_low_Head_0: THREE.Mesh
    TopRot001_low_Head_0: THREE.Mesh
    TopRot001_lowRigt_Head_0: THREE.Mesh
    Top_low_Head_0: THREE.Mesh
    TopRot002_lowRigt_Head_0: THREE.Mesh
    TopRot_lowRigt_Head_0: THREE.Mesh
    BottomSideRot_lowRight_Head_0: THREE.Mesh
    BottomSideRight_low_Head_0: THREE.Mesh
    BottomSideRot001_low_Head_0: THREE.Mesh
    BottomSideRot_low_Head_0: THREE.Mesh
    BottomSide_low_Head_0: THREE.Mesh
    BottomSideRot001_lowRight_Head_0: THREE.Mesh
    EyesRot001_low_Head_0: THREE.Mesh
    EyesRot_low_Head_0: THREE.Mesh
    Eyes_low_Head_0: THREE.Mesh
    EyesRot001_low001_Head_0: THREE.Mesh
    EyesRot001_low002_Head_0: THREE.Mesh
    Brain_low_Head_0: THREE.Mesh
    Plane002_Holograms_0: THREE.Mesh
    Sphere002_Holograms_0: THREE.Mesh
    Plane003_Holograms_0: THREE.Mesh
    SideRot_low_Head_0: THREE.Mesh
  }
  materials: {
    Head: THREE.MeshStandardMaterial
    Holograms: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function GhostInShell(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/digital-solutions/ghost-in-shell/scene-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  if (actions.Scene) {
    actions.Scene.play()
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.005}>
          <group name="SideRot001_low" position={[-65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot001_low_Head_0" geometry={nodes.SideRot001_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="SideRot002_low" position={[-65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot002_low_Head_0" geometry={nodes.SideRot002_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="SideRot003_low" position={[-65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot003_low_Head_0" geometry={nodes.SideRot003_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="sideRight_low" position={[65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="SideRot004_lowRight">
              <mesh name="SideRot004_lowRight_Head_0" geometry={nodes.SideRot004_lowRight_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="sideRight_low_Head_0" geometry={nodes.sideRight_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="side_low" position={[-65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="SideRot004_low">
              <mesh name="SideRot004_low_Head_0" geometry={nodes.SideRot004_low_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="side_low_Head_0" geometry={nodes.side_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="SideRot001_lowRight" position={[65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot001_lowRight_Head_0" geometry={nodes.SideRot001_lowRight_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="SideRot002_lowRight" position={[65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot002_lowRight_Head_0" geometry={nodes.SideRot002_lowRight_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="SideRot003_lowRight" position={[65.341, 111.463, 9.877]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="SideRot003_lowRight_Head_0" geometry={nodes.SideRot003_lowRight_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="TopRot002_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="TopRot002_low_Head_0" geometry={nodes.TopRot002_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="TopRot_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="TopRot_low_Head_0" geometry={nodes.TopRot_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="Top_low" position={[0, 65.478, 61.525]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="TopInner_low" position={[0, 0.615, -0.655]}>
              <mesh name="TopInner_low_Head_0" geometry={nodes.TopInner_low_Head_0.geometry} material={materials.Head} />
            </group>
            <group name="TopRot001_low" position={[0, 0.615, -0.655]}>
              <mesh name="TopRot001_low_Head_0" geometry={nodes.TopRot001_low_Head_0.geometry} material={materials.Head} />
            </group>
            <group name="TopRot001_lowRigt" position={[0, 0.615, -0.655]}>
              <mesh name="TopRot001_lowRigt_Head_0" geometry={nodes.TopRot001_lowRigt_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="Top_low_Head_0" geometry={nodes.Top_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="TopRot002_lowRigt" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="TopRot002_lowRigt_Head_0" geometry={nodes.TopRot002_lowRigt_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="TopRot_lowRigt" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="TopRot_lowRigt_Head_0" geometry={nodes.TopRot_lowRigt_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="BottomSideRight_low" position={[54.574, 46.296, 21]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="BottomSideRot_lowRight">
              <mesh name="BottomSideRot_lowRight_Head_0" geometry={nodes.BottomSideRot_lowRight_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="BottomSideRight_low_Head_0" geometry={nodes.BottomSideRight_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="BottomSideRot001_low" position={[-54.447, 46.468, 20.982]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="BottomSideRot001_low_Head_0" geometry={nodes.BottomSideRot001_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="BottomSide_low" position={[-54.574, 46.296, 21]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="BottomSideRot_low">
              <mesh name="BottomSideRot_low_Head_0" geometry={nodes.BottomSideRot_low_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="BottomSide_low_Head_0" geometry={nodes.BottomSide_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="BottomSideRot001_lowRight" position={[59.678, 39.345, 21.755]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="BottomSideRot001_lowRight_Head_0" geometry={nodes.BottomSideRot001_lowRight_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="Eyes_low" position={[0, 122.895, -23.015]} rotation={[-Math.PI / 2, 0, 0]} scale={8.159}>
            <group name="EyesRot001_low" scale={12.256}>
              <mesh name="EyesRot001_low_Head_0" geometry={nodes.EyesRot001_low_Head_0.geometry} material={materials.Head} />
            </group>
            <group name="EyesRot_low" scale={12.256}>
              <mesh name="EyesRot_low_Head_0" geometry={nodes.EyesRot_low_Head_0.geometry} material={materials.Head} />
            </group>
            <mesh name="Eyes_low_Head_0" geometry={nodes.Eyes_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="EyesRot001_low001" position={[-56.565, 122.733, -15.334]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="EyesRot001_low001_Head_0" geometry={nodes.EyesRot001_low001_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="EyesRot001_low002" position={[56.565, 122.733, -15.334]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="EyesRot001_low002_Head_0" geometry={nodes.EyesRot001_low002_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="Brain_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh name="Brain_low_Head_0" geometry={nodes.Brain_low_Head_0.geometry} material={materials.Head} />
          </group>
          <group name="Plane002" position={[0, 8.582, 4.912]} rotation={[Math.PI, -Math.PI / 4, 0]} scale={24.619}>
            <mesh name="Plane002_Holograms_0" geometry={nodes.Plane002_Holograms_0.geometry} material={materials.Holograms} />
          </group>
          <group name="Sphere002" position={[0, 98.266, 19.255]} rotation={[-Math.PI / 2, 0, 0]} scale={335.261}>
            <mesh name="Sphere002_Holograms_0" geometry={nodes.Sphere002_Holograms_0.geometry} material={materials.Holograms} />
          </group>
          <group name="Plane003" position={[0, 8.582, 4.912]} rotation={[0, -Math.PI / 4, 0]} scale={[24.619, 24.618, 24.619]}>
            <mesh name="Plane003_Holograms_0" geometry={nodes.Plane003_Holograms_0.geometry} material={materials.Holograms} />
          </group>
        </group>
        <mesh name="SideRot_low_Head_0" geometry={nodes.SideRot_low_Head_0.geometry} material={materials.Head} position={[-0.317, 0.541, 0.048]} rotation={[-Math.PI / 2, 0, 0]} scale={0.485} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/digital-solutions/ghost-in-shell/scene-transformed.glb')
