/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -k -K -t -T s 
Files: scene.gltf [103.87KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\digital-solutions\matrix\scene-transformed.glb [553.22KB] (-433%)
Author: Elin (https://sketchfab.com/ElinHohler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/matrix-void-abbe6f13ce8f477999fb0501476658bf
Title: Matrix Void
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_61: THREE.Mesh
    Object_65: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_70: THREE.Mesh
  }
  materials: {
    Color: THREE.MeshBasicMaterial
    Mask: THREE.MeshBasicMaterial
    wire: THREE.MeshBasicMaterial
    material: THREE.MeshBasicMaterial
    Alpha: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export default function Matrix(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/digital-solutions/matrix/scene-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  if (actions.Animation) {
    actions.Animation.play()
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="color003_19" position={[-1.883, 5.151, -0.867]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Color} />
          </group>
          <group name="color004_20" position={[0.831, 3.321, 1.612]}>
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Color} />
          </group>
          <group name="color011_21" position={[1.075, 5.151, -2.485]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Color} />
          </group>
          <group name="color012_22" position={[1.581, 3.321, -0.23]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Color} />
          </group>
          <group name="color013_23" position={[-1.237, 3.321, -2.589]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Color} />
          </group>
          <group name="color017_24" position={[2.049, 3.321, 2.098]}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Color} />
          </group>
          <group name="color021_25" position={[-0.07, 3.321, 1.248]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Color} />
          </group>
          <group name="color029_26" position={[0.873, 6.531, 2.497]} scale={1.947}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Color} />
          </group>
          <group name="color030_27" position={[-1.954, 4.562, 1.09]} scale={1.366}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Color} />
          </group>
          <group name="color031_28" position={[2.976, 4.562, 0.135]} scale={1.366}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Color} />
          </group>
          <group name="color032_29" position={[0.155, 4.562, -4.27]} scale={1.366}>
            <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Color} />
          </group>
          <group name="color033_30" position={[-2.965, 4.562, 4.437]} scale={1.366}>
            <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.Color} />
          </group>
          <group name="color037_31" position={[2.48, 8.471, -1.09]} scale={2.52}>
            <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Color} />
          </group>
          <group name="color038_32" position={[-3.249, 10.301, -1.991]} scale={2.52}>
            <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Color} />
          </group>
          <group name="color039_33" position={[-3.844, 8.471, 1.664]} scale={2.52}>
            <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.Color} />
          </group>
          <group name="color040_34" position={[-2.416, 8.471, -0.104]} scale={2.52}>
            <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Color} />
          </group>
          <group name="color041_35" position={[4.477, 8.471, 1.613]} scale={2.52}>
            <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Color} />
          </group>
          <group name="color042_36" position={[4.061, 11.672, -2.833]} scale={3.465}>
            <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Color} />
          </group>
          <group name="color043_37" position={[-1.631, 11.672, -4.473]} scale={3.465}>
            <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Color} />
          </group>
          <group name="Circle002_47" position={[0, -0.022, -0.061]} scale={2.136}>
            <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Color} />
          </group>
          <group name="Cylinder001_49" position={[0, -64.018, 0]} scale={0.071}>
            <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Color} />
          </group>
        </group>
        <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Mask} position={[-1.876, 0.874, -0.865]} rotation={[0, 1.205, 0]} />
        <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.Color} position={[1.763, 0, -1.304]} rotation={[Math.PI / 2, 0, 0.688]} scale={0.051} />
        <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.wire} position={[1.763, 0, -1.304]} rotation={[Math.PI / 2, 0, 0.688]} scale={0.051} />
        <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material} position={[1.743, 0, -1.372]} rotation={[-Math.PI, 0.809, -Math.PI]} scale={0.042} />
        <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Alpha} position={[0, 19.244, 0]} scale={8.942} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/digital-solutions/matrix/scene-transformed.glb')
