/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Desk.gltf -k -K -t -T s 
Files: Desk.gltf [21.53KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\desk\Desk-transformed.glb [1.3MB] (-5938%)
Author: Ankledot (https://sketchfab.com/Ankledot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-asset-ca972bf129344a73a3fe59a0eef78164
Title: Desk Asset
*/

import * as THREE from 'three'
import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Can_Momster_M_Can_Momster_0: THREE.Mesh
    Monitor_Wide_M_Monitor_Wide_0: THREE.Mesh
    Monitor_Wide_M_Monitor_Wide_Screen_0: THREE.Mesh
    Keyboard_M_Keyboard_0: THREE.Mesh
    Desk_M_Desk_Bottom_0: THREE.Mesh
    Desk_M_Desk_Top_0: THREE.Mesh
    ['1_M_HUION_KAMVAS_GT_221_PRO_0']: THREE.Mesh
  }
  materials: {
    M_Can_Momster: THREE.MeshStandardMaterial
    M_Monitor_Wide: THREE.MeshStandardMaterial
    M_Monitor_Wide_Screen: THREE.MeshStandardMaterial
    M_Keyboard: THREE.MeshStandardMaterial
    M_Desk_Bottom: THREE.MeshStandardMaterial
    M_Desk_Top: THREE.MeshStandardMaterial
    M_HUION_KAMVAS_GT_221_PRO: THREE.MeshStandardMaterial
  }
}

export default function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/desk/Desk-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Can_Momster_M_Can_Momster_0" geometry={nodes.Can_Momster_M_Can_Momster_0.geometry} material={materials.M_Can_Momster} position={[78.612, 42.852, -45.484]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="Monitor_Wide_M_Monitor_Wide_0" geometry={nodes.Monitor_Wide_M_Monitor_Wide_0.geometry} material={materials.M_Monitor_Wide} position={[75.127, 55.105, -73.996]} rotation={[-Math.PI / 2, 0, -0.737]} scale={100} />
        <mesh name="Monitor_Wide_M_Monitor_Wide_Screen_0" geometry={nodes.Monitor_Wide_M_Monitor_Wide_Screen_0.geometry} material={materials.M_Monitor_Wide_Screen} position={[75.127, 55.105, -73.996]} rotation={[-Math.PI / 2, 0, -0.737]} scale={100} />
        <mesh name="Keyboard_M_Keyboard_0" geometry={nodes.Keyboard_M_Keyboard_0.geometry} material={materials.M_Keyboard} position={[56.279, 37.56, -39.782]} rotation={[-Math.PI / 2, 0, -1.132]} scale={100} />
        <mesh name="Desk_M_Desk_Bottom_0" geometry={nodes.Desk_M_Desk_Bottom_0.geometry} material={materials.M_Desk_Bottom} position={[10.181, 6.957, -6.35]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="Desk_M_Desk_Top_0" geometry={nodes.Desk_M_Desk_Top_0.geometry} material={materials.M_Desk_Top} position={[10.181, 6.957, -6.35]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        {/* <mesh name="1_M_HUION_KAMVAS_GT_221_PRO_0" geometry={nodes['1_M_HUION_KAMVAS_GT_221_PRO_0'].geometry} material={materials.M_HUION_KAMVAS_GT_221_PRO} position={[12.173, 48.648, -73.081]} rotation={[-Math.PI / 2, 0, -0.217]} scale={100} >

          
          <Html
            position={[0, -0.03, 0.08]}   // Adjust as needed to align with surface
            rotation={[Math.PI / 2.48, 0, 0,]}
            scale={0.01}
            transform
            occlude="blending"
            zIndexRange={[1, 0]}      // Controls layering depth to stay on top
            style={{
              background: 'white',
              width: "100vw",
              height: '100vh'
            }}
          >
            <div style={{
              background: '#fff9db', padding: '4px 8px',
            }}>
              <h1>
                Choose a Case Study
              </h1>
              <div style={{ background: '#fff9db', padding: '4px 8px', zIndex: 5 }}>
                <button onClick={() => (alert("it works"))}>Button One</button>
                <button>Button Two</button>
                <button>Button Three</button>
              </div>

            </div>
          </Html>
        </mesh> */}
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/desk/Desk-transformed.glb')
