/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -k -K -t -T s 
Files: scene.gltf [158.36KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\digital-solutions\lens\scene-transformed.glb [322.27KB] (-104%)
Author: jvvince (https://sketchfab.com/JV0211)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lens-diaphragm-2e918ddad1d949e1bad80f82174eed34
Title: Lens Diaphragm
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'BluffTitler Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_7: THREE.Mesh
    Object_10: THREE.Mesh
    Object_13: THREE.Mesh
    Object_64: THREE.Mesh
    Object_117: THREE.Mesh
  }
  materials: {
    Material_3: THREE.MeshStandardMaterial
    Material_4: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
    Material_1: THREE.MeshStandardMaterial
    Material_2: THREE.MeshStandardMaterial
    Material_5: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Lens(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/digital-solutions/lens/scene-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  if (actions['BluffTitler Animation']) {
    actions['BluffTitler Animation'].play();
  } 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="BluffTitler_Text_Layer_8_34">
          <group name="Letter_I_35" position={[34.553, 109.561, -473.2]} rotation={[-0.021, -0.138, -0.148]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_36" position={[71.507, 93.528, -473.2]} rotation={[-0.087, -0.109, -0.677]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_37" position={[95.472, 61.141, -473.2]} rotation={[-0.13, -0.051, -1.2]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_38" position={[99.905, 21.098, -473.2]} rotation={[-0.138, 0.021, -1.721]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_39" position={[83.713, -15.787, -473.2]} rotation={[-0.109, 0.087, -2.243]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_40" position={[51.208, -39.589, -473.2]} rotation={[-0.051, 0.13, -2.769]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_41" position={[11.149, -43.85, -473.2]} rotation={[0.022, 0.138, 2.984]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_42" position={[-25.667, -27.498, -473.2]} rotation={[0.088, 0.108, 2.456]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_43" position={[-49.307, 5.124, -473.2]} rotation={[0.131, 0.05, 1.932]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_44" position={[-53.394, 45.199, -473.2]} rotation={[0.138, -0.022, 1.412]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_45" position={[-36.884, 81.948, -473.2]} rotation={[0.108, -0.088, 0.89]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Material_3} />
          </group>
          <group name="Letter_I_46" position={[-4.143, 105.425, -473.2]} rotation={[0.049, -0.131, 0.363]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Material_3} />
          </group>
        </group>
        <group name="BluffTitler_Text_Layer_9_47">
          <group name="Letter_I_48" position={[34.553, 109.561, -473.2]} rotation={[-0.021, -0.138, -0.148]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_49" position={[71.507, 93.528, -473.2]} rotation={[-0.087, -0.109, -0.677]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_50" position={[95.472, 61.141, -473.2]} rotation={[-0.13, -0.051, -1.2]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_51" position={[99.905, 21.098, -473.2]} rotation={[-0.138, 0.021, -1.721]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_52" position={[83.713, -15.787, -473.2]} rotation={[-0.109, 0.087, -2.243]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_53" position={[51.208, -39.589, -473.2]} rotation={[-0.051, 0.13, -2.769]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_54" position={[11.149, -43.85, -473.2]} rotation={[0.022, 0.138, 2.984]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_55" position={[-25.667, -27.498, -473.2]} rotation={[0.088, 0.108, 2.456]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_56" position={[-49.307, 5.124, -473.2]} rotation={[0.131, 0.05, 1.932]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_57" position={[-53.394, 45.199, -473.2]} rotation={[0.138, -0.022, 1.412]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_58" position={[-36.884, 81.948, -473.2]} rotation={[0.108, -0.088, 0.89]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.Material_4} />
          </group>
          <group name="Letter_I_59" position={[-4.143, 105.425, -473.2]} rotation={[0.049, -0.131, 0.363]} scale={[3, 0.4, 0.2]}>
            <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.Material_4} />
          </group>
        </group>
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material} position={[23.2, 32.8, -474.4]} scale={1.212} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material_0} position={[23.2, 32.8, -474.4]} scale={1.212} />
        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material_1} position={[39.326, 144.919, -462.057]} rotation={[0, 0, -0.143]} scale={[0.156, 0.156, 0.622]} />
        <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Material_2} position={[23.2, 32.8, -474.4]} />
        <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.Material_5} position={[23.2, 32.8, -472.8]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/digital-solutions/lens/scene-transformed.glb')
