/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 YouTube.gltf -k -K -t -T s 
Files: YouTube.gltf [5.51KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\youtube\YouTube-transformed.glb [63.46KB] (-1052%)
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-youtube-logo-43731340eb494e5a8a5375eb177c753f
Title: 3D Youtube Logo
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    glossy_putih: THREE.MeshStandardMaterial
    GLOSSY_YT: THREE.MeshStandardMaterial
  }
}

export default function YouTube(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/youtube/YouTube-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.glossy_putih} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.GLOSSY_YT} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/youtube/YouTube-transformed.glb')
