/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Email.gltf -k -K -t -T s 
Files: Email.gltf [4.55KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\email\Email-transformed.glb [167.16KB] (-3574%)
Author: Simon.Keating (https://sketchfab.com/Simon.Keating)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/email-icon-43e4588d176945e889004cf270e17cfa
Title: Email_Icon
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshPhysicalMaterial
  }
}

export default function Email(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/email/Email-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/email/Email-transformed.glb')
