/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 DysonSphere.gltf -t -T -k -K s 
Files: DysonSphere.gltf [334.01KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\dyson-sphere\DysonSphere-transformed.glb [4.36MB] (-1207%)
Author: Henrique777 (https://sketchfab.com/Henrique777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dyson-sphere-936f82626eaf42bd952d448762e229c8
Title: Dyson Sphere
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Sphere.003|Sphere.003Action' | 'Sphere.072|Sphere.192Action' | 'Sphere.192|Sphere.192Action' | 'Sphere.047|Sphere.192Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Sphere047_Esfera_0: THREE.Mesh
    Sphere072_Esfera_0: THREE.Mesh
    Sphere192_Esfera_0: THREE.Mesh
    Sphere003_Esfera016_0: THREE.Mesh
    Sphere054_Material050_0: THREE.Mesh
    Sphere007_Esfera_0: THREE.Mesh
    star_Star_0: THREE.Mesh
    Sphere001_Esfera021_0: THREE.Mesh
    Sphere001_Esfera022_0: THREE.Mesh
    star046_Star037_0: THREE.Mesh
    Sphere004_Material116_0: THREE.Mesh
  }
  materials: {
    Esfera: THREE.MeshStandardMaterial
    ['Esfera.016']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    Star: THREE.MeshStandardMaterial
    ['Esfera.021']: THREE.MeshStandardMaterial
    ['Esfera.022']: THREE.MeshStandardMaterial
    ['Star.037']: THREE.MeshStandardMaterial
    ['Material.116']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const DysonSphere: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF('/3d-objects/dyson-sphere/DysonSphere-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0}>
          <group name="Sphere047" position={[1201.489, 9786.951, -1032.903]} rotation={[-1.581, -0.004, -0.034]} scale={1115.998}>
            <mesh name="Sphere047_Esfera_0" geometry={nodes.Sphere047_Esfera_0.geometry} material={materials.Esfera} />
          </group>
          <group name="Sphere072" position={[1201.489, 9786.951, -1032.903]} rotation={[-1.581, -0.004, -0.034]} scale={1066.433}>
            <mesh name="Sphere072_Esfera_0" geometry={nodes.Sphere072_Esfera_0.geometry} material={materials.Esfera} />
          </group>
          <group name="Sphere192" position={[1201.489, 9786.951, -1032.903]} rotation={[2.531, Math.PI / 2, 0]} scale={1115.998}>
            <mesh name="Sphere192_Esfera_0" geometry={nodes.Sphere192_Esfera_0.geometry} material={materials.Esfera} />
          </group>
          <group name="Sphere003" position={[1025.548, 8643.089, -793.265]} rotation={[-1.561, -0.01, -0.064]} scale={[1356.733, 1292.393, 1325.549]}>
            <mesh name="Sphere003_Esfera016_0" geometry={nodes.Sphere003_Esfera016_0.geometry} material={materials['Esfera.016']} />
          </group>
        </group>
        <mesh name="Sphere054_Material050_0" geometry={nodes.Sphere054_Material050_0.geometry} material={materials['Material.050']} position={[1.007, 0.205, -0.193]} rotation={[-1.581, -0.004, -0.034]} scale={0} />
        <mesh name="Sphere007_Esfera_0" geometry={nodes.Sphere007_Esfera_0.geometry} material={materials.Esfera} position={[0.056, 0.454, -0.048]} rotation={[-1.581, -0.004, -0.034]} scale={0.052} />
        <mesh name="star_Star_0" geometry={nodes.star_Star_0.geometry} material={materials.Star} position={[0.061, 0.448, -0.046]} rotation={[-1.581, -0.004, -0.034]} scale={0.06} />
        <mesh name="Sphere001_Esfera021_0" geometry={nodes.Sphere001_Esfera021_0.geometry} material={materials['Esfera.021']} position={[0.061, 0.458, -0.041]} rotation={[2.491, 0.047, -1.732]} scale={0.033} />
        <mesh name="Sphere001_Esfera022_0" geometry={nodes.Sphere001_Esfera022_0.geometry} material={materials['Esfera.022']} position={[0.061, 0.458, -0.041]} rotation={[2.491, 0.047, -1.732]} scale={0.033} />
        <mesh name="star046_Star037_0" geometry={nodes.star046_Star037_0.geometry} material={materials['Star.037']} position={[0.111, 0.974, 0.589]} rotation={[-1.62, 0.602, -0.426]} scale={0.002} />
        <mesh name="Sphere004_Material116_0" geometry={nodes.Sphere004_Material116_0.geometry} material={materials['Material.116']} position={[0.026, 0.523, -0.048]} rotation={[1.704, 0.815, 2.831]} scale={0.08} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/dyson-sphere/DysonSphere-transformed.glb')
export default DysonSphere