/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 moneyBag.gltf -t -T -k -K s 
Files: moneyBag.gltf [15.5KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\money-bag\moneyBag-transformed.glb [296.26KB] (-1811%)
Author: Grindi (https://sketchfab.com/ranok777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/money-bag-wallet-with-dollar-embroidery-sign-e30a009ed66c4227bcc7d6ada8a07c7d
Title: Money bag wallet with dollar embroidery sign
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import {motion} from 'framer-motion-3d'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_12: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}

export default function MoneyBag(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/money-bag/moneyBag-transformed.glb') as GLTFResult

  const group = useRef<THREE.Group>(null);
  const radius = 6;
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    if (group.current) {  // Ensure that group.current is defined
      group.current.position.x = radius * Math.cos(elapsedTime);
      // group.current.position.y = (radius/2) * Math.sin(elapsedTime);
      group.current.position.z = radius * Math.sin(elapsedTime);
    }
  });
  return (
    <motion.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[7,0,0]} rotation={[0.25,2.25,0]}>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.479, 0.327, 0.155]} rotation={[-Math.PI / 2, -0.011, Math.PI / 2]} />
        <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial002} />
      </group>
    </motion.group>
  )
}

useGLTF.preload('/3d-objects/money-bag/moneyBag-transformed.glb')
