
export const gradientVariants = {
    'home-main': {
        background: `radial-gradient(#434343, #000, #202020)`,
        backgroundSize: '125% 125%',
        backgroundPosition: '0% 62.5%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'home-programmer': {
        background: 'radial-gradient(circle at center,#FF3CAC , #562B7C ,  #2B86C5)',
        backgroundSize: '200% 200%',
        backgroundPosition: '100% 0%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'home-investment': {
        background: 'radial-gradient(#101010, #0ba360, #3cba92)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 200%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'home-blog': {
        background: `radial-gradient(#434343, #000, #202020)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '100% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'programmer-main': {
        background: `radial-gradient(#434343, #000, #202020)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'programmer-overview-dynamic-zero': {
        background: "radial-gradient( #0f0c29, #302b63, #24243e)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-one': {
        background: "radial-gradient( #434343, #000000, #000000)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-two': {
        background: "radial-gradient( #434343, #434343, #000000)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-three': {
        background: "radial-gradient( #0f0c29, #302b63, #24243e)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-four': {
        background: "radial-gradient(  #434343, #000000, #000000)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-five': {
        background: "radial-gradient(#1cb5e0, #000046, #1cb5e0 )", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-six': {
        background: "radial-gradient(  #434343, #000000, #000000)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-seven': {
        background: "radial-gradient( #434343,#434343, #000000)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '250% 250%',
        backgroundPosition: '125% 125%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-eight': {
        background: "radial-gradient( #be93c5, #7bc6cc, #be93c5)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '100% 62.5%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-overview-dynamic-nine': {
        background: "radial-gradient(#16bffd,#16bffd, #cb3066)", /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        backgroundBlendMode:   `multiply`,
        backgroundSize: '400% 400%',
        backgroundPosition: '200% 200%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital': {
        background: 'radial-gradient(#0f2027, #203a43)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-one': {
        background: 'radial-gradient( #000000, #434343)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-two': {
        background: 'radial-gradient( #fffbd5, #b20a2c)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-three': {
        background: 'radial-gradient(#000000, #0f9b0f)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-four': {
        background: 'radial-gradient(#0f9b0f,#000000)',
        backgroundSize: '400% 400%',
        backgroundPosition: '0% 0%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-five': {
        background: 'radial-gradient(#005aa7, #fffde4)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '125% 125%',
        backgroundPosition: '50% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-six': {
        background: 'radial-gradient(#8e0e00, #1f1c18)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'programmer-why-digital-dynamic-zero': {
        background: 'radial-gradient(#1c92d2, #f2fcfe)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'approach-main': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'approach-agile-development': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'approach-agile-development-dynamic': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'approach-design-thinking': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'approach-design-thinking-dynamic': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'approach-technology-stack': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'approach-process-flow': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'approach-process-flow-dynamic': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'lets-work-consultation': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'lets-work-contact-information': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'lets-work-location-information': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'digital-solutions-main': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'custom-software-development': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'custom-software-dynamic-zero': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'custom-software-dynamic-one': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'custom-software-dynamic-two': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'data-science-ai': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'data-science-ai-dynamic-zero': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'data-science-ai-dynamic-one': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'data-science-ai-dynamic-two': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'web-mobile-application': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'web-mobile-application-dynamic-zero': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'web-mobile-application-dynamic-one': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'web-mobile-application-dynamic-two': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'digital-transformation': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'digital-transformation-zero': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
    'digital-transformation-dynamic-one': {
        background: 'radial-gradient(circle at center,#0ba360 , #000060 , #3cba92)',
        backgroundSize: '200% 200%',
        backgroundPosition: '150% 150%',
        animation: 'animate-approach-bg 8s ease-in-out infinite alternate',
    },
    'digital-transformation-dynamic-two': {
        background: `radial-gradient(circle at center,#000, #232526, #414345)`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 0%',
        animation: 'animate-main-bg 10s infinite alternate',
    },
    'digital-solutions-visuals': {
        background: 'radial-gradient(circle at center,#1f4037, #99f2c8, #99f2c8)',
        backgroundBlendMode:   `multiply`,
        backgroundSize: '200% 200%',
        backgroundPosition: '0% 50%',
        animation: 'animate-area-bg 6s ease-in-out infinite alternate',
    },
};