/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Phone.gltf -k -K -t -T s 
Files: Phone.gltf [3.44KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\phone\Phone-transformed.glb [15.39KB] (-347%)
Author: Alexander (https://sketchfab.com/pravdin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/telephone-receiver-3d-icon-f69ff8c7e4a84a5e807ab3069bfbf67b
Title: Telephone Receiver (3D Icon)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export default function Phone(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/phone/Phone-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Material} position={[0.001, -0.001, -0.002]} rotation={[0, 0, 0.934]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/phone/Phone-transformed.glb')
