/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 MagnifyingGlass.gltf -t -T -k -K s 
Files: MagnifyingGlass.gltf [12.75KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\magnifying-glass\MagnifyingGlass-transformed.glb [380.48KB] (-2884%)
Author: godisme1220 (https://sketchfab.com/godisme1220)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/physically-based-rendering-magnifier-gltf-847f15958d5e49b5aa994fadcfec6b32
Title: Physically Based Rendering Magnifier (glTF)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    ['.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

const MagnifyingGlass: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/magnifying-glass/MagnifyingGlass-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Empty001_2">
            <group name="Cylinder002_0" rotation={[-Math.PI / 2, 0.96, 0]} scale={0.81}>
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['.001']} />
              <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
            </group>
            <group name="Cylinder003_1" rotation={[-Math.PI / 2, 0.96, 0]} scale={0.81}>
              <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.004']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/magnifying-glass/MagnifyingGlass-transformed.glb');
export default MagnifyingGlass
