/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 lightBulb.gltf -t -T -k -K s 
Files: lightBulb.gltf [6.82KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\light-bulb\lightBulb-transformed.glb [193.86KB] (-2743%)
Author: JacquelineM (https://sketchfab.com/JacquelineM)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/light-bulb-b05d65aada034ccebdc73d5982108ea2
Title: Light Bulb
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { MotionGroup } from '@/app/_hide/_components/framer/MotionGroup'
import type { HTMLMotionProps } from 'framer-motion';



type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    transparente_del_foco: THREE.MeshStandardMaterial
  }
}

export default function LightBulbModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('/3d-objects/light-bulb/lightBulb-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <MotionGroup name="Sketchfab_Scene">
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.transparente_del_foco} rotation={[-Math.PI / 2, 0, 0]} />
      </MotionGroup>
    </group>
  )
}

useGLTF.preload('/3d-objects/light-bulb/lightBulb-transformed.glb')
