/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hive.gltf -k -K -t -T s 
Files: hive.gltf [7.88KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\hive\hive-transformed.glb [586.55KB] (-7344%)
Author: Matt LeMoine (https://sketchfab.com/Matt_LeMoine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hive-1b0b7c4eebe24dd384f7803e60380582
Title: Hive
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Comb_Comb_0: THREE.Mesh
    Hive_Hive_0: THREE.Mesh
  }
  materials: {
    Comb: THREE.MeshStandardMaterial
    Hive: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/core-values/hive/hive-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Comb_Comb_0" geometry={nodes.Comb_Comb_0.geometry} material={materials.Comb} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh name="Hive_Hive_0" geometry={nodes.Hive_Hive_0.geometry} material={materials.Hive} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/hive/hive-transformed.glb')
