/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -T -k -K s 
Files: scene.gltf [6.54KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\newspaper-box\scene-transformed.glb [687.59KB] (-10414%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    news_box__002__glass: THREE.MeshStandardMaterial
    news_box__001__case: THREE.MeshStandardMaterial
  }
}

export default function NewspaperBox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/newspaper-box/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.news_box__002__glass} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.news_box__001__case} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/newspaper-box/scene-transformed.glb')
