/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 TikTok.gltf -k -K -t -T s 
Files: TikTok.gltf [8.71KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\tiktok\TikTok-transformed.glb [71.86KB] (-725%)
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-tiktok-logo-7c287b247b13465d8d284870d5aac26b
Title: 3D Tiktok Logo
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
  }
  materials: {
    tiktok_2_GLOSS: THREE.MeshStandardMaterial
    ['glossy_putih.006']: THREE.MeshStandardMaterial
    tiktok_3_GLOSS: THREE.MeshStandardMaterial
    glossy_tiktok: THREE.MeshStandardMaterial
  }
}

export default function TikTok(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/tiktok/TikTok-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.tiktok_2_GLOSS} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={5.999} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['glossy_putih.006']} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={5.999} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.tiktok_3_GLOSS} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={5.999} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.glossy_tiktok} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={5.999} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/tiktok/TikTok-transformed.glb')
