/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 YingYang.gltf -k -K -t -T s 
Files: YingYang.gltf [11.47KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\ying-yang\YingYang-transformed.glb [45.76KB] (-299%)
Author: OuterspaceSoftware (https://sketchfab.com/OuterspaceSoftware)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yin-yang-4d41f70662c34a94b732e36b480782bb
Title: Yin Yang
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'BluffTitler Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.Mesh
    Object_10: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function YinYang(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/ying-yang/YingYang-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="BluffTitler_Vector_Layer_4_2">
          <group name="Vector_3" position={[25, 0, -375.005]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material} />
          </group>
        </group>
        <group name="BluffTitler_Vector_Layer_5_4">
          <group name="Vector_5" position={[25, -24.995, -400]} rotation={[0, 0, Math.PI / 2]}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/ying-yang/YingYang-transformed.glb')
