/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 house.gltf -t -T -k -K s 
Files: house.gltf [515.16KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\house\house-transformed.glb [455.09KB] (12%)
Author: Zhenya (https://sketchfab.com/evgeniya93svg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/autumn-house-52772448c62348e0a4951b51758d5587
Title: Autumn House
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    House_roof_windows_01_lambert16_0: THREE.Mesh
    House_roof_part_01_House_part01_mat_0: THREE.Mesh
    polySurface529_lambert14_0: THREE.Mesh
    initialShadingGrouppolySurface116_polySurface3_lambert17_0: THREE.Mesh
    polySurface637_lambert15_0: THREE.Mesh
    polySurface638_lambert18_0: THREE.Mesh
  }
  materials: {
    lambert16: THREE.MeshStandardMaterial
    House_part01_mat: THREE.MeshStandardMaterial
    lambert14: THREE.MeshStandardMaterial
    lambert17: THREE.MeshStandardMaterial
    lambert15: THREE.MeshStandardMaterial
    lambert18: THREE.MeshStandardMaterial
  }
}

export default function House(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/house/house-transformed.glb') as GLTFResult

  const group = useRef<THREE.Group>(null);
  const radius = 6;
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    if (group.current) {  // Ensure that group.current is defined
      // group.current.position.x = radius * Math.cos(elapsedTime);
      group.current.position.y = radius * Math.sin(elapsedTime);
      group.current.position.z = radius * Math.cos(elapsedTime);
    }
  });
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[0,-25,25]} rotation={[0.25,0.5,0]}>
        <mesh name="House_roof_windows_01_lambert16_0" geometry={nodes.House_roof_windows_01_lambert16_0.geometry} material={materials.lambert16} />
        <mesh name="House_roof_part_01_House_part01_mat_0" geometry={nodes.House_roof_part_01_House_part01_mat_0.geometry} material={materials.House_part01_mat} />
        <mesh name="polySurface529_lambert14_0" geometry={nodes.polySurface529_lambert14_0.geometry} material={materials.lambert14} />
        <mesh name="initialShadingGrouppolySurface116_polySurface3_lambert17_0" geometry={nodes.initialShadingGrouppolySurface116_polySurface3_lambert17_0.geometry} material={materials.lambert17} />
        <mesh name="polySurface637_lambert15_0" geometry={nodes.polySurface637_lambert15_0.geometry} material={materials.lambert15} />
        <mesh name="polySurface638_lambert18_0" geometry={nodes.polySurface638_lambert18_0.geometry} material={materials.lambert18} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/house/house-transformed.glb')
