/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PumpingHeart.gltf -k -K -t -T s 
Files: PumpingHeart.gltf [6.38KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\pumping-heart\PumpingHeart-transformed.glb [15.64KB] (-145%)
Author: omarelone (https://sketchfab.com/omarelone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pumping-heart-model-6f815b9822dc479eae0a17b8dcab9c75
Title: PUMPING HEART MODEL
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['BASE_HEART_Material_#41_0']: THREE.Mesh
  }
  materials: {
    Material_41: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/core-values/pumping-heart/PumpingHeart-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="BASE_HEART" position={[-0.676, 38.876, -0.255]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Object_5" position={[-0.09, 0, -38.876]}>
              <mesh name="BASE_HEART_Material_#41_0" geometry={nodes['BASE_HEART_Material_#41_0'].geometry} material={materials.Material_41} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/pumping-heart/PumpingHeart-transformed.glb')
