/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Bee.gltf -k -K -t -T s 
Files: Bee.gltf [547.53KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\bee\Bee-transformed.glb [1.85MB] (-239%)
Author: Shrikant (https://sketchfab.com/kfivedrag)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/honey-bee-4d0142c47688483caba624c9bf55b963
Title: Honey Bee | 🦟
*/

import * as THREE from 'three'
import React from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = '_bee_idle' | '_bee_hover' | '_bee_take_off_and_land'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_116: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export interface BeeThreeProps  {
  animation: ActionName;
  props: JSX.IntrinsicElements['group'];
}
export default function Model(props: BeeThreeProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/3d-objects/core-values/bee/Bee-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useFrame(()=> {
    if (actions[props.animation]) {
      actions[props.animation]!.play()
    }
  })
  return (
    <group ref={group} {...props.props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_0} skeleton={nodes.Object_116.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/bee/Bee-transformed.glb')
