/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Paper.gltf -k -K -t -T s 
Files: Paper.gltf [4.34KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\paper\Paper-transformed.glb [55.82KB] (-1186%)
Author: pozo3d (https://sketchfab.com/pozo3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/folded-wrinkled-paper-9a1d10ebb9a241ffa37b6f6df4adc1f0
Title: Folded Wrinkled Paper
*/

import * as THREE from 'three'
import React, { useEffect, useState } from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ICaseStudy } from '@/app/_database/models/case-study'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    blinn1SG: THREE.MeshStandardMaterial
  }
}

export interface ThreeProps {
  props?: JSX.IntrinsicElements['group'];
};

interface PaperThreeProps extends ThreeProps {
  caseStudy?: ICaseStudy|undefined|null;
}



export default function Paper(props: PaperThreeProps) {
  const { nodes, materials } = useGLTF('/3d-objects/paper/Paper-transformed.glb') as GLTFResult

  const calculateScalingFactor = (width: number) => {
    // As the window gets smaller, the scaling factor increases
    if (width >= 1920) return 1; // Max width, smallest scaling factor
    if (width > 700) return Math.min(Math.max(1920 / width, 1), 6); // Moderate scaling for medium screens
    return Math.min(Math.max(1920 / width, 0.5), 5); // Higher scaling for very small screens
};
const calculateScalingHeightFactor = (width: number) => {
    // As the window gets smaller, the scaling factor increases
    if (width >= 1920) return 1; // Max width, smallest scaling factor
    if (width > 700) return Math.min(Math.max(1920 / width, 0.3), 0.7); // Moderate scaling for medium screens
    return Math.min(Math.max(1920 / width, 0.5), 1); // Higher scaling for very small screens
};

const [scalingFactor, setScalingFactor] = useState(() =>
  calculateScalingFactor(window.innerWidth)
);
const [heightScalingFactor, setHeightScalingFactor] = useState(() =>
  calculateScalingHeightFactor(window.innerWidth)
);
useEffect(() => {
    const handleResize = () => {
        setScalingFactor(calculateScalingFactor(window.innerWidth));
        setHeightScalingFactor(calculateScalingHeightFactor(window.innerWidth));
    };

    window.addEventListener('resize', handleResize);

    // Cleanup event listener on component unmount
    return () => {
        window.removeEventListener('resize', handleResize);
    };
}, []);

  if (props.caseStudy) {
    return (
      <group  dispose={null}>
        <group name="Sketchfab_Scene">
          <mesh castShadow receiveShadow name="Object_2" geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} >


            {/* Overlaying HTML */}
            <Html
              position={[0, 0, 0.155]}   // Adjust as needed to align with surface
              rotation={[0, 0, -Math.PI / 2]}
              transform
              occlude="blending"
              zIndexRange={[1, 0]}      // Controls layering depth to stay on top
              scale={1}
              style={{
                width: `${40 * scalingFactor}vw`,
                height: `${100 * heightScalingFactor}vh`,
                background: '#fff9db',
                color:'black'
              }}
            >
              <div style={{ background: '#fff9db', padding: '4px 8px', width:'100%'   }}>
                <h1>
                  {props.caseStudy.title}
                </h1>
                <div style={{ background: '#fff9db', padding: '4px 8px', width: '100%', height: '100%' }}>
                  <h6>
                    Summary
                  </h6>
                  <ul>
                    <li>
                      {props.caseStudy.summary}
                    </li>

                  </ul>
                </div>
                <div style={{ background: '#fff9db', padding: '4px 8px', width: '100%', height: '100%' }}>
                  <h6>
                    Objectives
                  </h6>
                  <ul>
                    {
                      props.caseStudy.objectives.map((o) => (
                        <li key={o}>
                          {o}
                        </li>
                      ))
                    }


                  </ul>
                </div>
                <div style={{ background: '#fff9db', padding: '4px 8px', width: '100%', height: '100%' }}>
                  <h6>
                    Challenges
                  </h6>
                  <ul>
                    {
                      props.caseStudy.challenges.map((c) => (
                        <li key={c}>
                          {c}
                        </li>
                      ))
                    }


                  </ul>
                </div>
                <div style={{ background: '#fff9db', padding: '4px 8px', width: '100%', height: '100%' }}>
                  <h6>
                    Solutions
                  </h6>
                  <ul>
                    {
                      props.caseStudy.solutions.map((s) => (
                        <li key={s}>
                          {s}
                        </li>
                      ))
                    }


                  </ul>
                </div>
                <div style={{ background: '#fff9db', padding: '4px 8px', width: '100%', height: '100%' }}>
                  <h6>
                    Outcome
                  </h6>
                  <ul>

                    <li >
                      {props.caseStudy.outcomes.description}
                    </li>


                  </ul>
                </div>

              </div>
            </Html>
          </mesh>
        </group>
      </group>
    )
  }

}

useGLTF.preload('/3d-objects/paper/Paper-transformed.glb')
