/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 City.gltf -k -K -t -T s 
Files: City.gltf [137.18KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\city\City-transformed.glb [446.06KB] (-225%)
Author: Mafer Luna (https://sketchfab.com/Fernanda.Aldaco.de.Luna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mafer-city-2bd53c28a598423f81e883224332dfd1
Title: Mafer_City
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Main'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Blimp_Window_0: THREE.Mesh
    Car_Blue_Wheels_0: THREE.Mesh
    Car_Green_Wheels_0: THREE.Mesh
    Car_Yellow_Wheels_0: THREE.Mesh
    Hot_air_balloon_Orange_Basket_0: THREE.Mesh
    Wheel_of_fortune_Grey_material2_0: THREE.Mesh
    Boat_White_material2_0: THREE.Mesh
    Boat_box__0: THREE.Mesh
    Water_Water_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function City(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/core-values/city/City-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Blimp" position={[8184.433, 31244.307, -26948.424]} rotation={[0, 1.484, 0]}>
            <mesh name="Blimp_Window_0" geometry={nodes.Blimp_Window_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Car_Blue" position={[10878.602, 5249.237, 3013.11]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Object_39" position={[-38137.965, -4707.782, -1733.075]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Car_Blue_Wheels_0" geometry={nodes.Car_Blue_Wheels_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
          <group name="Car_Green" position={[37275.281, 5251.068, -3251.509]} rotation={[-Math.PI / 2, 0, 0.004]}>
            <group name="Object_46" position={[7448.795, -38155.301, -1731.908]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
              <mesh name="Car_Green_Wheels_0" geometry={nodes.Car_Green_Wheels_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
          <group name="Car_Yellow" position={[982.417, 5203.481, -6254.487]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="Object_53" position={[-38156.66, -2120.14, -1682.673]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Car_Yellow_Wheels_0" geometry={nodes.Car_Yellow_Wheels_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
          <group name="Hot_air_balloon" position={[-7176.889, 11696.895, -23828.648]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Hot_air_balloon_Orange_Basket_0" geometry={nodes.Hot_air_balloon_Orange_Basket_0.geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Wheel_of_fortune" position={[28070.945, 10103.538, 10031.881]} rotation={[-Math.PI / 2, -0.385, 0]}>
            <group name="Object_98" position={[494.878, -645.215, 1220.478]} rotation={[Math.PI / 2, 0, -0.385]} scale={1.194}>
              <mesh name="Wheel_of_fortune_Grey_material2_0" geometry={nodes.Wheel_of_fortune_Grey_material2_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
        </group>
        <mesh name="Boat_White_material2_0" geometry={nodes.Boat_White_material2_0.geometry} material={materials.PaletteMaterial001} position={[-122.311, 31.83, 279.086]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Boat_box__0" geometry={nodes.Boat_box__0.geometry} material={materials.PaletteMaterial002} position={[-122.341, 48.979, 258.507]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Water_Water_0" geometry={nodes.Water_Water_0.geometry} material={materials.PaletteMaterial003} position={[-22.651, 3.681, 7.156]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/city/City-transformed.glb')
