/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 SwissArmyKnife.gltf -t -T -k -K s 
Files: SwissArmyKnife.gltf [38.25KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\swiss-army-knife\SwissArmyKnife-transformed.glb [1.31MB] (-3334%)
Author: Htwest (https://sketchfab.com/Htwest)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/swiss-army-knife-0fbda6eebd9b481ab232fa8ec5e46d58
Title: Swiss Army Knife
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    pHelix1_Metal_0: THREE.Mesh
    Bottle_Opener_Metal_0: THREE.Mesh
    Bottle_Opener_2_Metal_0: THREE.Mesh
    ['0']: THREE.Mesh
    Large_Knife_Metal_0: THREE.Mesh
    Small_knife_Metal_0: THREE.Mesh
    TopPlate_standardSurface3_0: THREE.Mesh
    Spring_top_Metal_0: THREE.Mesh
    Pillar3_Pillar4_0: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    standardSurface3: THREE.MeshStandardMaterial
    Pillar4: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const SwissArmyKnife: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/swiss-army-knife/SwissArmyKnife-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Knife" position={[0.012, 0, 0.077]} scale={0.01}>
          <group name="pHelix1" position={[-0.953, -0.161, -8.075]}>
            <mesh name="pHelix1_Metal_0" geometry={nodes.pHelix1_Metal_0.geometry} material={materials.Metal} />
          </group>
        </group>
        <group name="Top" position={[0.012, 0, 0.077]} scale={0.01}>
          <group name="Bottle_Opener" position={[-4.196, 0.025, -7.495]}>
            <mesh name="Bottle_Opener_Metal_0" geometry={nodes.Bottle_Opener_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group name="Bottle_Opener_2" position={[1.447, 0.023, -7.654]}>
            <mesh name="Bottle_Opener_2_Metal_0" geometry={nodes.Bottle_Opener_2_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group name="Poky_knife" position={[-0.991, 0.021, -8.102]}>
            <mesh name="0" geometry={nodes['0'].geometry} material={materials.Metal} />
          </group>
        </group>
        <group name="Bottom" position={[0.012, 0, 0.077]} scale={0.01}>
          <group name="Large_Knife" position={[1.442, -0.078, -7.664]}>
            <mesh name="Large_Knife_Metal_0" geometry={nodes.Large_Knife_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group name="Small_knife" position={[-4.199, -0.057, -7.52]}>
            <mesh name="Small_knife_Metal_0" geometry={nodes.Small_knife_Metal_0.geometry} material={materials.Metal} />
          </group>
        </group>
        <mesh name="TopPlate_standardSurface3_0" geometry={nodes.TopPlate_standardSurface3_0.geometry} material={materials.standardSurface3} position={[0.012, 0, 0.077]} scale={0.01} />
        <mesh name="Spring_top_Metal_0" geometry={nodes.Spring_top_Metal_0.geometry} material={materials.Metal} position={[0.012, 0, 0.077]} scale={0.01} />
        <mesh name="Pillar3_Pillar4_0" geometry={nodes.Pillar3_Pillar4_0.geometry} material={materials.Pillar4} position={[-0.029, 0, 0.002]} scale={0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/swiss-army-knife/SwissArmyKnife-transformed.glb');
export default SwissArmyKnife;
