/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Messenger.gltf -k -K -t -T s 
Files: Messenger.gltf [4.17KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\messenger\Messenger-transformed.glb [19.35KB] (-364%)
Author: bariacg (https://sketchfab.com/bariacg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/messenger-logo-ff6081e0ff594da1bb1edf6e8bca4371
Title: Messenger Logo
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['messenger_Material_#26_0']: THREE.Mesh
  }
  materials: {
    Material_26: THREE.MeshStandardMaterial
  }
}

export default function Messenger(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/messenger/Messenger-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="messenger_Material_#26_0" geometry={nodes['messenger_Material_#26_0'].geometry} material={materials.Material_26} position={[0, 91.527, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/messenger/Messenger-transformed.glb')
