/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Book.gltf -k -K -t -T s 
Files: Book.gltf [625.98KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\core-values\book\Book-transformed.glb [1.53MB] (-144%)
Author: Canary Games (https://sketchfab.com/CapAlatriste)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/9-magic-book-3december2019-4e245fa384fb486ba7bbc519bdc24464
Title: #9 Magic Book - 3December2019
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_113: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_137: THREE.Mesh
    Object_139: THREE.Mesh
    Object_141: THREE.Mesh
    Object_143: THREE.Mesh
    Object_145: THREE.Mesh
    Object_147: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_157: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_163: THREE.Mesh
    Object_165: THREE.Mesh
    Object_167: THREE.Mesh
    Object_169: THREE.Mesh
    Object_171: THREE.Mesh
    Object_173: THREE.Mesh
    Object_175: THREE.Mesh
    Object_177: THREE.Mesh
    Object_179: THREE.Mesh
    Object_181: THREE.Mesh
    Object_183: THREE.Mesh
    Object_185: THREE.Mesh
    Object_187: THREE.Mesh
    Object_189: THREE.Mesh
    Object_191: THREE.Mesh
    Object_193: THREE.Mesh
    Object_195: THREE.Mesh
    Object_197: THREE.Mesh
    Object_199: THREE.Mesh
    Object_201: THREE.Mesh
    Object_203: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_211: THREE.Mesh
    Object_213: THREE.Mesh
    Object_215: THREE.Mesh
    Object_217: THREE.Mesh
    Object_219: THREE.Mesh
    Object_221: THREE.Mesh
    Object_223: THREE.Mesh
    Object_225: THREE.Mesh
    Object_227: THREE.Mesh
    Object_229: THREE.Mesh
    Object_231: THREE.Mesh
    Object_233: THREE.Mesh
    Object_235: THREE.Mesh
    Object_237: THREE.Mesh
    Object_239: THREE.Mesh
    Object_241: THREE.Mesh
    Object_243: THREE.Mesh
    Object_245: THREE.Mesh
    Object_247: THREE.Mesh
    Object_249: THREE.Mesh
    Object_251: THREE.Mesh
    Object_253: THREE.Mesh
    Object_255: THREE.Mesh
    Object_257: THREE.Mesh
    Object_259: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
    Object_265: THREE.Mesh
    Object_267: THREE.Mesh
    Object_269: THREE.Mesh
    Object_271: THREE.Mesh
    Object_273: THREE.Mesh
    Object_275: THREE.Mesh
    Object_277: THREE.Mesh
    Object_279: THREE.Mesh
    Object_281: THREE.Mesh
    Object_283: THREE.Mesh
    Object_285: THREE.Mesh
    Object_287: THREE.Mesh
    Object_289: THREE.Mesh
    Object_291: THREE.Mesh
    Object_293: THREE.Mesh
    Object_295: THREE.Mesh
    Object_297: THREE.Mesh
    Object_299: THREE.Mesh
    Object_301: THREE.Mesh
    Object_303: THREE.Mesh
    Object_305: THREE.Mesh
    Object_307: THREE.Mesh
    Object_309: THREE.Mesh
    Object_311: THREE.Mesh
    Object_313: THREE.Mesh
    Object_315: THREE.Mesh
    Object_317: THREE.Mesh
    Object_319: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_327: THREE.Mesh
    Object_329: THREE.Mesh
    Object_331: THREE.Mesh
    Object_333: THREE.Mesh
    Object_335: THREE.Mesh
    Object_337: THREE.Mesh
    Object_339: THREE.Mesh
    Object_341: THREE.Mesh
    Object_343: THREE.Mesh
    Object_345: THREE.Mesh
    Object_347: THREE.Mesh
    Object_349: THREE.Mesh
    Object_351: THREE.Mesh
    Object_353: THREE.Mesh
    Object_355: THREE.Mesh
    Object_357: THREE.Mesh
    Object_359: THREE.Mesh
    Object_361: THREE.Mesh
    Object_363: THREE.Mesh
    Object_365: THREE.Mesh
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    Stars: THREE.MeshStandardMaterial
    Book_Diary: THREE.MeshStandardMaterial
    Book_Pages: THREE.MeshStandardMaterial
    Book_Tapa: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Book(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/core-values/book/Book-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Book_0" position={[-0.096, 0.123, 0.592]} rotation={[-2.327, -0.237, -2.897]}>
          <group name="Stars_6" position={[5.81, 0.988, 5.41]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(1)_7" position={[4.7, 1.238, 4.4]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(2)_8" position={[2.59, 1.678, 5.01]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(3)_9" position={[1.6, 1.838, 3.39]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(4)_10" position={[2.21, 1.738, 0.5]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(5)_11" position={[5.81, 0.978, -1.07]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(6)_12" position={[1.95, 1.758, -3.6]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(7)_13" position={[4.47, 1.258, -3.69]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(8)_14" position={[3.44, 1.478, -1.64]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(9)_15" position={[4.1, 1.328, 1.97]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(10)_16" position={[6.06, 0.948, 1.25]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(11)_17" position={[5.34, 0.927, 3.28]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(12)_18" position={[5.05, 0.927, 2.59]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(13)_19" position={[3.06, 1.337, 2.72]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(14)_20" position={[2.89, 1.357, 1.46]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(15)_21" position={[3.86, 1.177, 0.09]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(16)_22" position={[4.36, 1.097, -3.06]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(17)_23" position={[1.18, 1.747, -2.44]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(18)_24" position={[3.64, 1.277, -4.31]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(19)_25" position={[2.67, 1.447, -2.41]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(20)_26" position={[3.27, 1.317, 3.77]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(21)_27" position={[3.87, 1.217, -0.84]} rotation={[-1.309, 0.045, -0.012]} scale={0.1}>
            <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(22)_28" position={[1.471, 1.463, -4.336]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(23)_29" position={[2.602, 1.383, -3.328]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(24)_30" position={[4.742, 1.214, -3.941]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(25)_31" position={[5.752, 1.145, -2.322]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(26)_32" position={[5.007, 0.716, 0.569]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(27)_33" position={[1.381, 1.094, 2.144]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(28)_34" position={[5.306, 0.801, 4.668]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(29)_35" position={[2.743, 0.982, 4.762]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(30)_36" position={[3.773, 0.856, 2.71]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(31)_37" position={[3.1, 0.915, -0.899]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(32)_38" position={[1.181, 1.325, -0.176]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(33)_39" position={[1.846, 1.04, -2.207]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(34)_40" position={[2.127, 0.996, -1.517]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(35)_41" position={[4.181, 0.964, -1.65]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(36)_42" position={[4.412, 1.16, -0.39]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(37)_43" position={[3.442, 1.28, 0.981]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(38)_44" position={[2.924, 1.265, 4.132]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(39)_45" position={[6.11, 0.863, 3.507]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(40)_46" position={[3.642, 1.152, 5.381]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(41)_47" position={[4.62, 1.062, 3.479]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(42)_48" position={[3.998, 1.097, -2.7]} rotation={[-1.845, 0.301, -3.057]} scale={0.1}>
            <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(43)_49" position={[3.229, 1.353, 1.68]} rotation={[-1.856, 0.405, -3.014]} scale={0.1}>
            <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(44)_50" position={[1.672, 1.826, -4.55]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(45)_51" position={[2.807, 1.645, -3.554]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(46)_52" position={[4.924, 1.28, -4.19]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(47)_53" position={[5.921, 1.056, -2.582]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(48)_54" position={[5.35, 1.175, 0.315]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(49)_55" position={[1.742, 1.787, 1.929]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(50)_56" position={[5.646, 1.079, 4.412]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(51)_57" position={[3.12, 1.542, 4.532]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(52)_58" position={[4.136, 1.377, 2.47]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(53)_59" position={[3.426, 1.497, -1.132]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(54)_60" position={[1.472, 1.862, -0.388]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(55)_61" position={[2.192, 1.792, -2.426]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(56)_62" position={[2.469, 1.584, -1.74]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(57)_63" position={[4.469, 1.233, -1.894]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(58)_64" position={[4.648, 1.183, -0.637]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(59)_65" position={[3.696, 1.367, 0.745]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(60)_66" position={[3.237, 1.463, 3.901]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(61)_67" position={[6.426, 0.899, 3.242]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(62)_68" position={[3.987, 1.359, 5.142]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(63)_69" position={[4.93, 1.169, 3.231]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(64)_70" position={[4.254, 1.297, -2.942]} rotation={[-1.285, 0.411, -0.104]} scale={0.1}>
            <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(65)_71" position={[3.031, 1.222, 2.055]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(66)_72" position={[1.11, 1.777, -4.179]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(67)_73" position={[2.232, 1.576, -3.178]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(68)_74" position={[4.687, 1.374, -3.643]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(69)_75" position={[5.694, 1.197, -2.032]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(70)_76" position={[4.927, 0.841, 0.863]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(71)_77" position={[1.37, 1.592, 2.463]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(72)_78" position={[5.258, 0.884, 4.961]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(73)_79" position={[2.729, 1.331, 5.072]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(74)_80" position={[3.728, 1.104, 3.013]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(75)_81" position={[3.042, 1.242, -0.591]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(76)_82" position={[1.181, 1.848, 0.145]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(77)_83" position={[1.8, 1.5, -1.891]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_169" geometry={nodes.Object_169.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(78)_84" position={[2.075, 1.392, -1.203]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(79)_85" position={[4.114, 1.147, -1.35]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_173" geometry={nodes.Object_173.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(80)_86" position={[3.834, 1.472, -0.253]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(81)_87" position={[2.89, 1.689, 1.125]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(82)_88" position={[2.394, 1.721, 4.279]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_179" geometry={nodes.Object_179.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(83)_89" position={[5.516, 0.99, 3.633]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(84)_90" position={[3.103, 1.531, 5.523]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(85)_91" position={[4.055, 1.343, 3.615]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_185" geometry={nodes.Object_185.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(86)_92" position={[3.401, 1.458, -2.56]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(87)_93" position={[2.841, 1.569, 2.055]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(88)_94" position={[0.84, 1.596, -4.53]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_191" geometry={nodes.Object_191.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(89)_95" position={[1.973, 1.424, -3.529]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(90)_96" position={[4.094, 1.07, -4.156]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_195" geometry={nodes.Object_195.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(91)_97" position={[5.909, 0.892, -2.544]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_197" geometry={nodes.Object_197.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(92)_98" position={[5.326, 1.011, 0.351]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(93)_99" position={[1.708, 1.604, 1.95]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(94)_100" position={[5.607, 0.923, 4.448]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_203" geometry={nodes.Object_203.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(95)_101" position={[3.078, 1.371, 4.559]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_205" geometry={nodes.Object_205.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(96)_102" position={[4.102, 1.209, 2.501]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(97)_103" position={[3.405, 1.319, -1.104]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(98)_104" position={[1.446, 1.673, -0.368]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(99)_105" position={[2.174, 1.605, -2.404]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(100)_106" position={[2.45, 1.497, -1.716]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(101)_107" position={[4.452, 1.158, -1.862]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(102)_108" position={[4.184, 1.072, -0.383]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(103)_109" position={[3.226, 1.252, 0.995]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(104)_110" position={[2.755, 1.349, 4.149]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(105)_111" position={[5.949, 0.804, 3.503]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(106)_112" position={[3.501, 1.252, 5.393]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(107)_113" position={[4.452, 1.065, 3.485]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(108)_114" position={[3.798, 1.179, -2.69]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(109)_115" position={[3.238, 1.29, 1.925]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(110)_116" position={[1.317, 1.844, -4.309]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(111)_117" position={[2.439, 1.644, -3.308]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(112)_118" position={[4.546, 1.253, -3.935]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_239" geometry={nodes.Object_239.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(113)_119" position={[5.365, 1.177, -3.434]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_241" geometry={nodes.Object_241.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(114)_120" position={[4.597, 0.821, -0.539]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_243" geometry={nodes.Object_243.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(115)_121" position={[1.04, 1.572, 1.06]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(116)_122" position={[4.929, 0.863, 3.558]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_247" geometry={nodes.Object_247.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(117)_123" position={[2.4, 1.311, 3.669]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_249" geometry={nodes.Object_249.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(118)_124" position={[3.398, 1.083, 1.611]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(119)_125" position={[2.712, 1.222, -1.994]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(120)_126" position={[0.851, 1.828, -1.258]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_255" geometry={nodes.Object_255.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(121)_127" position={[1.471, 1.479, -3.294]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(122)_128" position={[1.746, 1.372, -2.606]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(123)_129" position={[3.785, 1.126, -2.752]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_261" geometry={nodes.Object_261.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(124)_130" position={[4.043, 1.231, -0.161]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_263" geometry={nodes.Object_263.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(125)_131" position={[3.099, 1.449, 1.217]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_265" geometry={nodes.Object_265.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(126)_132" position={[2.603, 1.481, 4.371]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_267" geometry={nodes.Object_267.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(127)_133" position={[5.725, 0.749, 3.725]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_269" geometry={nodes.Object_269.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(128)_134" position={[3.312, 1.29, 5.615]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(129)_135" position={[4.263, 1.103, 3.707]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(130)_136" position={[3.61, 1.218, -2.467]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_275" geometry={nodes.Object_275.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(131)_137" position={[3.05, 1.328, 2.147]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(132)_138" position={[1.513, 1.712, -4.09]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_279" geometry={nodes.Object_279.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(133)_139" position={[2.646, 1.539, -3.089]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(134)_140" position={[4.767, 1.186, -3.716]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_283" geometry={nodes.Object_283.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(135)_141" position={[6.017, 1.128, -2.548]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(136)_142" position={[5.434, 1.248, 0.347]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(137)_143" position={[1.816, 1.84, 1.947]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(138)_144" position={[5.715, 1.16, 4.445]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(139)_145" position={[3.186, 1.608, 4.556]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(140)_146" position={[4.21, 1.445, 2.497]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(141)_147" position={[3.513, 1.555, -1.107]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(142)_148" position={[1.554, 1.91, -0.371]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(143)_149" position={[2.282, 1.841, -2.407]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(144)_150" position={[2.558, 1.734, -1.719]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_303" geometry={nodes.Object_303.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(145)_151" position={[4.56, 1.395, -1.866]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(146)_152" position={[4.289, 0.998, -0.289]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(147)_153" position={[3.331, 1.178, 1.089]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_309" geometry={nodes.Object_309.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(148)_154" position={[2.86, 1.276, 4.243]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(149)_155" position={[6.054, 0.73, 3.597]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(150)_156" position={[3.605, 1.178, 5.487]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_315" geometry={nodes.Object_315.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(151)_157" position={[4.557, 0.991, 3.579]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(152)_158" position={[3.903, 1.106, -2.596]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(153)_159" position={[3.343, 1.216, 2.019]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(154)_160" position={[1.422, 1.771, -4.215]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(155)_161" position={[2.544, 1.57, -3.214]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(156)_162" position={[4.651, 1.18, -3.841]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_327" geometry={nodes.Object_327.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(157)_163" position={[5.624, 1.287, -2.867]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(158)_164" position={[4.856, 0.931, 0.028]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(159)_165" position={[1.3, 1.682, 1.627]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(160)_166" position={[5.188, 0.974, 4.125]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(161)_167" position={[2.659, 1.421, 4.236]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(162)_168" position={[3.658, 1.194, 2.178]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(163)_169" position={[2.971, 1.332, -1.427]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(164)_170" position={[1.11, 1.938, -0.691]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(165)_171" position={[1.73, 1.59, -2.727]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(166)_172" position={[2.005, 1.483, -2.039]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(167)_173" position={[4.044, 1.237, -2.185]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_349" geometry={nodes.Object_349.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(168)_174" position={[4.4, 1.37, -0.921]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(169)_175" position={[3.456, 1.587, 0.457]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(170)_176" position={[2.96, 1.619, 3.611]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_355" geometry={nodes.Object_355.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(171)_177" position={[6.082, 0.887, 2.965]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(172)_178" position={[3.669, 1.429, 4.855]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(173)_179" position={[4.621, 1.241, 2.947]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_361" geometry={nodes.Object_361.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(174)_180" position={[3.967, 1.356, -3.228]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_363" geometry={nodes.Object_363.geometry} material={materials.Stars} />
          </group>
          <group name="Stars_(175)_181" position={[3.407, 1.467, 1.387]} rotation={[-1.285, 0.404, -0.106]} scale={0.1}>
            <mesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.Stars} />
          </group>
        </group>
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Book_Diary} position={[-0.096, 0.123, 0.592]} rotation={[-2.327, -0.237, -2.897]} />
        <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Book_Pages} position={[-0.096, 0.123, 0.592]} rotation={[-2.327, -0.237, -2.897]} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Book_Tapa} position={[-0.096, 0.123, 0.592]} rotation={[-2.327, -0.237, -2.897]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/core-values/book/Book-transformed.glb')
