/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -k -K -t -T s 
Files: scene.gltf [607KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\digital-solutions\network\scene-transformed.glb [1.56MB] (-157%)
Author: davideformentiarranz (https://sketchfab.com/davideformentiarranz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/network-2-2f6525a91f4647a181aa3c72ce5fa36b
Title: Network 2
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'CINEMA_4D_Principale'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cilindro_0__0: THREE.Mesh
    Cilindro_1__0: THREE.Mesh
    Cilindro_2__0: THREE.Mesh
    Cilindro_3__0: THREE.Mesh
    Cilindro_4_2__0: THREE.Mesh
    Cilindro_5__0: THREE.Mesh
    Cilindro_6_2__0: THREE.Mesh
    Cilindro_7__0: THREE.Mesh
    Cilindro_8__0: THREE.Mesh
    Cilindro_9_2__0: THREE.Mesh
    Cilindro_10_2__0: THREE.Mesh
    Cilindro_11_2__0: THREE.Mesh
    Cilindro_12__0: THREE.Mesh
    Cilindro_13__0: THREE.Mesh
    Cilindro_14__0: THREE.Mesh
    Cilindro_15__0: THREE.Mesh
    Cilindro_16__0: THREE.Mesh
    Cilindro_17_2__0: THREE.Mesh
    Cilindro_18__0: THREE.Mesh
    Cilindro_19_2__0: THREE.Mesh
    Cilindro_20__0: THREE.Mesh
    Cilindro_21__0: THREE.Mesh
    Cilindro_22_2__0: THREE.Mesh
    Cilindro_23__0: THREE.Mesh
    Cilindro_24_2__0: THREE.Mesh
    Cilindro_25_2__0: THREE.Mesh
    Cilindro_26_2__0: THREE.Mesh
    Cilindro_27__0: THREE.Mesh
    Cilindro_28__0: THREE.Mesh
    Cilindro_29_2__0: THREE.Mesh
    Cilindro_30__0: THREE.Mesh
    Cilindro_31__0: THREE.Mesh
    Cilindro_32__0: THREE.Mesh
    Cilindro_33__0: THREE.Mesh
    Cilindro_34__0: THREE.Mesh
    Cilindro_35_2__0: THREE.Mesh
    Cilindro_36_2__0: THREE.Mesh
    Cilindro_37_2__0: THREE.Mesh
    Cilindro_38__0: THREE.Mesh
    Cilindro_39__0: THREE.Mesh
    Cilindro_40_2__0: THREE.Mesh
    Cilindro_41_2__0: THREE.Mesh
    Cilindro_42_2__0: THREE.Mesh
    Cilindro_43__0: THREE.Mesh
    Cilindro_44_2__0: THREE.Mesh
    Cilindro_45__0: THREE.Mesh
    Cilindro_46__0: THREE.Mesh
    Cilindro_47__0: THREE.Mesh
    Cilindro_48_2__0: THREE.Mesh
    Cilindro_49__0: THREE.Mesh
    Cilindro_50__0: THREE.Mesh
    Cilindro_51__0: THREE.Mesh
    Cilindro_52_2__0: THREE.Mesh
    Cilindro_53__0: THREE.Mesh
    Cilindro_54_2__0: THREE.Mesh
    Cilindro_55__0: THREE.Mesh
    Cilindro_56_2__0: THREE.Mesh
    Cilindro_57_2__0: THREE.Mesh
    Cilindro_58__0: THREE.Mesh
    Cilindro_59__0: THREE.Mesh
    Cilindro_60__0: THREE.Mesh
    Cilindro_61__0: THREE.Mesh
    Cilindro_62_2__0: THREE.Mesh
    Cilindro_63__0: THREE.Mesh
    Cilindro_64__0: THREE.Mesh
    Cilindro_65__0: THREE.Mesh
    Cilindro_66_2__0: THREE.Mesh
    Cilindro_67__0: THREE.Mesh
    Cilindro_68__0: THREE.Mesh
    Cilindro_69__0: THREE.Mesh
    Cilindro_70__0: THREE.Mesh
    Cilindro_71__0: THREE.Mesh
    Cilindro_72__0: THREE.Mesh
    Cilindro_73__0: THREE.Mesh
    Cilindro_74__0: THREE.Mesh
    Cilindro_75__0: THREE.Mesh
    Cilindro_76__0: THREE.Mesh
    Cilindro_77__0: THREE.Mesh
    Cilindro_78__0: THREE.Mesh
    Cilindro_79__0: THREE.Mesh
    Cilindro_80_2__0: THREE.Mesh
    Cilindro_81_2__0: THREE.Mesh
    Cilindro_82_2__0: THREE.Mesh
    Cilindro_83__0: THREE.Mesh
    Cilindro_84_2__0: THREE.Mesh
    Cilindro_85__0: THREE.Mesh
    Cilindro_86__0: THREE.Mesh
    Cilindro_87_2__0: THREE.Mesh
    Cilindro_88__0: THREE.Mesh
    Cilindro_89_2__0: THREE.Mesh
    Cilindro_90__0: THREE.Mesh
    Cilindro_91_2__0: THREE.Mesh
    Cilindro_92_2__0: THREE.Mesh
    Cilindro_93_2__0: THREE.Mesh
    Cilindro_94__0: THREE.Mesh
    Cilindro_95_2__0: THREE.Mesh
    Cilindro_96__0: THREE.Mesh
    Cilindro_97__0: THREE.Mesh
    Cilindro_98_2__0: THREE.Mesh
    Cilindro_99__0: THREE.Mesh
    Cilindro_100__0: THREE.Mesh
    Cilindro_101__0: THREE.Mesh
    Cilindro_102__0: THREE.Mesh
    Cilindro_103__0: THREE.Mesh
    Cilindro_104__0: THREE.Mesh
    Cilindro_105__0: THREE.Mesh
    Cilindro_106__0: THREE.Mesh
    Cilindro_107__0: THREE.Mesh
    Cilindro_108_2__0: THREE.Mesh
    Cilindro_109__0: THREE.Mesh
    Cilindro_110__0: THREE.Mesh
    Cilindro_111__0: THREE.Mesh
    Cilindro_112__0: THREE.Mesh
    Cilindro_113__0: THREE.Mesh
    Cilindro_114__0: THREE.Mesh
    Cilindro_115_2__0: THREE.Mesh
    Cilindro_116_2__0: THREE.Mesh
    Cilindro_117__0: THREE.Mesh
    Cilindro_118__0: THREE.Mesh
    Cilindro_119__0: THREE.Mesh
    Sfera_0__0: THREE.Mesh
    Sfera_1__0: THREE.Mesh
    Sfera_2__0: THREE.Mesh
    Sfera_3__0: THREE.Mesh
    Sfera_4__0: THREE.Mesh
    Sfera_5__0: THREE.Mesh
    Sfera_6__0: THREE.Mesh
    Sfera_7__0: THREE.Mesh
    Sfera_8__0: THREE.Mesh
    Sfera_9__0: THREE.Mesh
    Sfera_10__0: THREE.Mesh
    Sfera_11__0: THREE.Mesh
    Sfera_12__0: THREE.Mesh
    Sfera_13__0: THREE.Mesh
    Sfera_14__0: THREE.Mesh
    Sfera_15__0: THREE.Mesh
    Sfera_16__0: THREE.Mesh
    Sfera_17__0: THREE.Mesh
    Sfera_18__0: THREE.Mesh
    Sfera_19__0: THREE.Mesh
    Sfera_20__0: THREE.Mesh
    Sfera_21__0: THREE.Mesh
    Sfera_22__0: THREE.Mesh
    Sfera_23__0: THREE.Mesh
    Sfera_24__0: THREE.Mesh
    Sfera_25__0: THREE.Mesh
    Sfera_26__0: THREE.Mesh
    Sfera_27__0: THREE.Mesh
    Sfera_28__0: THREE.Mesh
    Sfera_29__0: THREE.Mesh
    Sfera_30__0: THREE.Mesh
    Sfera_31__0: THREE.Mesh
    Sfera_32__0: THREE.Mesh
    Sfera_33__0: THREE.Mesh
    Sfera_34__0: THREE.Mesh
    Sfera_35__0: THREE.Mesh
    Sfera_36__0: THREE.Mesh
    Sfera_37__0: THREE.Mesh
    Sfera_38__0: THREE.Mesh
    Sfera_39__0: THREE.Mesh
    Sfera_40__0: THREE.Mesh
    Sfera_41__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Network(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/digital-solutions/network/scene-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  if (actions.CINEMA_4D_Principale) {
    actions.CINEMA_4D_Principale.play()
  }
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Clona_1" scale={0.01}>
          <group name="Cilindro_0" position={[-43.167, 144.503, 26.265]} rotation={[1.869, -0.515, 1.704]} scale={[1, 0.377, 1]}>
            <mesh name="Cilindro_0__0" geometry={nodes.Cilindro_0__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_1" position={[-33.599, 135.36, 35.449]} rotation={[1.822, -0.484, -1.835]} scale={[1, 0.269, 1]}>
            <mesh name="Cilindro_1__0" geometry={nodes.Cilindro_1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_2" position={[-66.125, 154.439, 36.065]} rotation={[2.338, -0.021, -0.636]} scale={[1, 0.161, 1]}>
            <mesh name="Cilindro_2__0" geometry={nodes.Cilindro_2__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_3" position={[58.547, 144.016, 37.098]} rotation={[1.896, 0.298, 1.639]} scale={[1, 0.726, 1]}>
            <mesh name="Cilindro_3__0" geometry={nodes.Cilindro_3__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_4" position={[96.652, 119.999, 72.692]} rotation={[2.836, -0.317, -2.542]} scale={[1, 0.58, 1]}>
            <group name="Cilindro_4_2">
              <mesh name="Cilindro_4_2__0" geometry={nodes.Cilindro_4_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_5" position={[27.464, 101.407, 61.243]} rotation={[2.087, -0.087, -0.729]} scale={[1, 0.574, 1]}>
            <mesh name="Cilindro_5__0" geometry={nodes.Cilindro_5__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_6" position={[4.506, 111.343, 71.043]} rotation={[1.742, -0.444, -1.139]} scale={[1, 0.745, 1]}>
            <group name="Cilindro_6_2">
              <mesh name="Cilindro_6_2__0" geometry={nodes.Cilindro_6_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_7" position={[37.93, 78.127, 158.138]} rotation={[1.841, -0.553, -2.637]} scale={[1, 0.672, 1]}>
            <mesh name="Cilindro_7__0" geometry={nodes.Cilindro_7__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_8" position={[-23.133, 112.079, 132.344]} rotation={[1.928, -0.019, -0.344]} scale={[1, 0.99, 1]}>
            <mesh name="Cilindro_8__0" geometry={nodes.Cilindro_8__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_9" position={[135.344, 123.927, 27.441]} rotation={[3.1, -1.247, 2.577]} scale={[1, 0.447, 1]}>
            <group name="Cilindro_9_2">
              <mesh name="Cilindro_9_2__0" geometry={nodes.Cilindro_9_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_10" position={[104.261, 81.318, 51.585]} rotation={[2.741, -0.804, -1.935]} scale={[1, 0.597, 1]}>
            <group name="Cilindro_10_2">
              <mesh name="Cilindro_10_2__0" geometry={nodes.Cilindro_10_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_11" position={[151.063, 20.12, 54.655]} rotation={[2.382, -0.88, 2.985]} scale={[1, 0.815, 1]}>
            <group name="Cilindro_11_2">
              <mesh name="Cilindro_11_2__0" geometry={nodes.Cilindro_11_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_12" position={[137.35, -6.443, 103.99]} rotation={[2.866, -0.484, -0.59]} scale={[1, 0.443, 1]}>
            <mesh name="Cilindro_12__0" geometry={nodes.Cilindro_12__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_13" position={[129.241, 58.683, 55.669]} rotation={[2.285, -0.73, 0.325]} scale={[1, 0.577, 1]}>
            <mesh name="Cilindro_13__0" geometry={nodes.Cilindro_13__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_14" position={[90.549, 54.756, 100.921]} rotation={[2.077, -0.619, -1.128]} scale={[1, 0.34, 1]}>
            <mesh name="Cilindro_14__0" geometry={nodes.Cilindro_14__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_15" position={[62.91, 55.492, 162.221]} rotation={[3.031, -0.846, -1.361]} scale={[1, 0.812, 1]}>
            <mesh name="Cilindro_15__0" geometry={nodes.Cilindro_15__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_16" position={[128.184, 144.28, -25.288]} rotation={[1.332, -0.603, 0.007]} scale={[1, 0.761, 1]}>
            <mesh name="Cilindro_16__0" geometry={nodes.Cilindro_16__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_17" position={[135.794, 105.598, -46.396]} rotation={[1.53, -1.262, 2.715]} scale={[1, 0.57, 1]}>
            <group name="Cilindro_17_2">
              <mesh name="Cilindro_17_2__0" geometry={nodes.Cilindro_17_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_18" position={[138.488, 64.398, -85.799]} rotation={[0.157, -1.162, 0.4]} scale={[1, 0.637, 1]}>
            <mesh name="Cilindro_18__0" geometry={nodes.Cilindro_18__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_19" position={[158.626, 12.49, -24.16]} rotation={[0.188, -1.349, 1.947]} scale={[1, 0.503, 1]}>
            <group name="Cilindro_19_2">
              <mesh name="Cilindro_19_2__0" geometry={nodes.Cilindro_19_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_20" position={[148.772, 74.044, -37.486]} rotation={[1.179, -1.296, -1.108]} scale={[1, 0.831, 1]}>
            <mesh name="Cilindro_20__0" geometry={nodes.Cilindro_20__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_21" position={[155.932, 53.691, 15.243]} rotation={[2.11, -1.048, -0.828]} scale={[1, 0.353, 1]}>
            <mesh name="Cilindro_21__0" geometry={nodes.Cilindro_21__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_22" position={[164.041, -11.435, 63.565]} rotation={[2.835, -1.395, -2.576]} scale={[1, 0.52, 1]}>
            <group name="Cilindro_22_2">
              <mesh name="Cilindro_22_2__0" geometry={nodes.Cilindro_22_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_23" position={[106.396, 148.336, 3.601]} rotation={[1.347, 0.182, -0.433]} scale={[1, 0.518, 1]}>
            <mesh name="Cilindro_23__0" geometry={nodes.Cilindro_23__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_24" position={[106.846, 130.007, -70.235]} rotation={[1.373, 0.078, 0.644]} scale={[1, 0.364, 1]}>
            <group name="Cilindro_24_2">
              <mesh name="Cilindro_24_2__0" geometry={nodes.Cilindro_24_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_25" position={[53.474, 117.929, -105.15]} rotation={[1.269, -0.112, -0.45]} scale={[1, 0.73, 1]}>
            <group name="Cilindro_25_2">
              <mesh name="Cilindro_25_2__0" geometry={nodes.Cilindro_25_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_26" position={[46.697, 106.594, -178.193]} rotation={[0.696, 0.389, 1.488]} scale={[1, 0.269, 1]}>
            <group name="Cilindro_26_2">
              <mesh name="Cilindro_26_2__0" geometry={nodes.Cilindro_26_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_27" position={[78.28, 122.728, -114.388]} rotation={[1.429, 0.127, 3.049]} scale={[1, 0.742, 1]}>
            <mesh name="Cilindro_27__0" geometry={nodes.Cilindro_27__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_28" position={[100.069, 118.672, -143.278]} rotation={[0.964, -0.591, 2.436]} scale={[1, 0.531, 1]}>
            <mesh name="Cilindro_28__0" geometry={nodes.Cilindro_28__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_29" position={[109.922, 57.118, -129.952]} rotation={[-0.178, -0.885, 0.762]} scale={[1, 0.879, 1]}>
            <group name="Cilindro_29_2">
              <mesh name="Cilindro_29_2__0" geometry={nodes.Cilindro_29_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_30" position={[37.208, 129.744, -7.848]} rotation={[1.65, 0.035, 0.957]} scale={[1, 0.586, 1]}>
            <mesh name="Cilindro_30__0" geometry={nodes.Cilindro_30__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_31" position={[-62.968, 171.193, -36.143]} rotation={[1.667, 0.117, 0.199]} scale={[1, 0.647, 1]}>
            <mesh name="Cilindro_31__0" geometry={nodes.Cilindro_31__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_32" position={[-30.443, 152.114, -36.759]} rotation={[1.871, -0.341, 2.84]} scale={[1, 0.707, 1]}>
            <mesh name="Cilindro_32__0" geometry={nodes.Cilindro_32__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_33" position={[17.407, 156.433, -70.256]} rotation={[1.528, -0.336, 1.942]} scale={[1, 0.769, 1]}>
            <mesh name="Cilindro_33__0" geometry={nodes.Cilindro_33__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_34" position={[-14.176, 140.299, -134.06]} rotation={[0.563, 0.244, 0.628]} scale={[1, 0.633, 1]}>
            <mesh name="Cilindro_34__0" geometry={nodes.Cilindro_34__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_35" position={[-34.478, 123.265, -107.109]} rotation={[-0.009, 0.49, 0.312]} scale={[1, 0.583, 1]}>
            <group name="Cilindro_35_2">
              <mesh name="Cilindro_35_2__0" geometry={nodes.Cilindro_35_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_36" position={[1.589, 84.761, -142.003]} rotation={[-0.021, 0.919, 2.055]} scale={[1, 0.378, 1]}>
            <group name="Cilindro_36_2">
              <mesh name="Cilindro_36_2__0" geometry={nodes.Cilindro_36_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_37" position={[-123.331, 114.48, -35.159]} rotation={[1.919, 0.955, -1.104]} scale={[1, 0.924, 1]}>
            <group name="Cilindro_37_2">
              <mesh name="Cilindro_37_2__0" geometry={nodes.Cilindro_37_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_38" position={[-110.607, 122.09, -98.183]} rotation={[0.678, 0.542, 2.125]} scale={[1, 0.828, 1]}>
            <mesh name="Cilindro_38__0" geometry={nodes.Cilindro_38__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_39" position={[-94.841, 66.553, -106.125]} rotation={[-0.071, 0.115, 1.594]} scale={[1, 0.767, 1]}>
            <mesh name="Cilindro_39__0" geometry={nodes.Cilindro_39__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_40" position={[-184.9, 30.535, -86.682]} rotation={[0.411, 1.037, -0.779]} scale={[1, 0.39, 1]}>
            <group name="Cilindro_40_2">
              <mesh name="Cilindro_40_2__0" geometry={nodes.Cilindro_40_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_41" position={[-108.772, 31.71, -95.608]} rotation={[0.057, 0.234, 1.931]} scale={[1, 0.989, 1]}>
            <group name="Cilindro_41_2">
              <mesh name="Cilindro_41_2__0" geometry={nodes.Cilindro_41_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_42" position={[-154.558, 42.083, -52.314]} rotation={[2.532, 0.96, 2.573]} scale={[1, 0.532, 1]}>
            <group name="Cilindro_42_2">
              <mesh name="Cilindro_42_2__0" geometry={nodes.Cilindro_42_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_43" position={[-168.489, 7.24, -41.797]} rotation={[3.136, 0.849, -1.813]} scale={[1, 0.473, 1]}>
            <mesh name="Cilindro_43__0" geometry={nodes.Cilindro_43__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_44" position={[-85.891, 108.662, 44.835]} rotation={[2.66, 0.751, -2.902]} scale={[1, 0.587, 1]}>
            <group name="Cilindro_44_2">
              <mesh name="Cilindro_44_2__0" geometry={nodes.Cilindro_44_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_45" position={[-133.53, 59.56, -17.205]} rotation={[2.61, 1.055, -1.03]} scale={[1, 0.885, 1]}>
            <mesh name="Cilindro_45__0" geometry={nodes.Cilindro_45__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_46" position={[-117.118, 36.264, 27.68]} rotation={[1.751, 0.84, -0.787]} scale={[1, 0.445, 1]}>
            <mesh name="Cilindro_46__0" geometry={nodes.Cilindro_46__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_47" position={[-153.473, 31.706, 68.971]} rotation={[1.472, 0.374, -1.635]} scale={[1, 0.618, 1]}>
            <mesh name="Cilindro_47__0" geometry={nodes.Cilindro_47__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_48" position={[-174.501, 14.229, 33.862]} rotation={[0.593, 0.791, 1.214]} scale={[1, 0.552, 1]}>
            <group name="Cilindro_48_2">
              <mesh name="Cilindro_48_2__0" geometry={nodes.Cilindro_48_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_49" position={[-76.324, 99.518, 54.019]} rotation={[2.244, 0.993, -2.345]} scale={[1, 0.506, 1]}>
            <mesh name="Cilindro_49__0" geometry={nodes.Cilindro_49__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_50" position={[-63.869, 55.601, 197.759]} rotation={[2.977, 0.328, -1.813]} scale={[1, 0.807, 1]}>
            <mesh name="Cilindro_50__0" geometry={nodes.Cilindro_50__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_51" position={[-97.294, 88.817, 110.665]} rotation={[1.731, 0.839, 0.692]} scale={[1, 0.955, 1]}>
            <mesh name="Cilindro_51__0" geometry={nodes.Cilindro_51__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_52" position={[-117.06, 43.04, 119.434]} rotation={[1.396, 0.771, 0.497]} scale={[1, 0.613, 1]}>
            <group name="Cilindro_52_2">
              <mesh name="Cilindro_52_2__0" geometry={nodes.Cilindro_52_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_53" position={[-174.444, 21.005, 125.617]} rotation={[2.587, 0.93, -1.3]} scale={[1, 0.633, 1]}>
            <mesh name="Cilindro_53__0" geometry={nodes.Cilindro_53__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_54" position={[70.062, -151.916, 26.878]} rotation={[-1.43, 0.389, -1.403]} scale={[1, 0.738, 1]}>
            <group name="Cilindro_54_2">
              <mesh name="Cilindro_54_2__0" geometry={nodes.Cilindro_54_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_55" position={[50.318, -145.314, 60.519]} rotation={[-1.353, 0.301, 1.168]} scale={[1, 0.542, 1]}>
            <mesh name="Cilindro_55__0" geometry={nodes.Cilindro_55__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_56" position={[117.658, -170.921, 44.454]} rotation={[-1.893, -0.218, 2.605]} scale={[1, 0.396, 1]}>
            <group name="Cilindro_56_2">
              <mesh name="Cilindro_56_2__0" geometry={nodes.Cilindro_56_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_57" position={[-61.41, -151.384, 45.104]} rotation={[-1.721, -0.373, -1.594]} scale={[1, 0.689, 1]}>
            <group name="Cilindro_57_2">
              <mesh name="Cilindro_57_2__0" geometry={nodes.Cilindro_57_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_58" position={[-117.48, -150.994, 77.095]} rotation={[-2.324, 0.222, 0.208]} scale={[1, 0.4, 1]}>
            <mesh name="Cilindro_58__0" geometry={nodes.Cilindro_58__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_59" position={[-53.348, -125.92, 74.935]} rotation={[-1.684, -0.058, 2.086]} scale={[1, 0.646, 1]}>
            <mesh name="Cilindro_59__0" geometry={nodes.Cilindro_59__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_60" position={[-5.752, -144.924, 92.51]} rotation={[-1.512, 0.193, 1.696]} scale={[1, 1.064, 1]}>
            <mesh name="Cilindro_60__0" geometry={nodes.Cilindro_60__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_61" position={[-73.461, -124.067, 131.231]} rotation={[-2.225, 0.362, 1.088]} scale={[1, 0.434, 1]}>
            <mesh name="Cilindro_61__0" geometry={nodes.Cilindro_61__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_62" position={[30.205, -143.462, 116.816]} rotation={[-2.511, -0.273, 2.085]} scale={[1, 0.807, 1]}>
            <group name="Cilindro_62_2">
              <mesh name="Cilindro_62_2__0" geometry={nodes.Cilindro_62_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_63" position={[146.071, -74.935, 96.046]} rotation={[-2.475, -0.784, -2.554]} scale={[1, 0.334, 1]}>
            <mesh name="Cilindro_63__0" geometry={nodes.Cilindro_63__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_64" position={[83.104, -91.17, 96.238]} rotation={[-2.899, -0.073, -1.279]} scale={[1, 0.522, 1]}>
            <mesh name="Cilindro_64__0" geometry={nodes.Cilindro_64__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_65" position={[96.205, -61.241, 103.169]} rotation={[-3.003, -0.039, 1.321]} scale={[1, 0.65, 1]}>
            <mesh name="Cilindro_65__0" geometry={nodes.Cilindro_65__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_66" position={[135.186, -141.193, 49.965]} rotation={[-2.403, -1.111, 3.048]} scale={[1, 0.535, 1]}>
            <group name="Cilindro_66_2">
              <mesh name="Cilindro_66_2__0" geometry={nodes.Cilindro_66_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_67" position={[115.442, -134.591, 83.606]} rotation={[-2.683, -0.439, 0.587]} scale={[1, 0.349, 1]}>
            <mesh name="Cilindro_67__0" geometry={nodes.Cilindro_67__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_68" position={[65.576, -120.897, 90.728]} rotation={[-3.098, -0.321, -0.66]} scale={[1, 0.556, 1]}>
            <mesh name="Cilindro_68__0" geometry={nodes.Cilindro_68__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_69" position={[-2.133, -100.04, 129.449]} rotation={[-3.115, -0.646, 1.112]} scale={[1, 0.494, 1]}>
            <mesh name="Cilindro_69__0" geometry={nodes.Cilindro_69__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_70" position={[150.94, -41.364, 56.634]} rotation={[-1.466, -1.279, -1.013]} scale={[1, 0.736, 1]}>
            <mesh name="Cilindro_70__0" geometry={nodes.Cilindro_70__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_71" position={[148.146, -62.795, -65.736]} rotation={[-0.107, -1.029, -0.006]} scale={[1, 0.66, 1]}>
            <mesh name="Cilindro_71__0" geometry={nodes.Cilindro_71__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_72" position={[158.431, -53.148, -17.423]} rotation={[-1.267, -1.447, 1.372]} scale={[1, 0.866, 1]}>
            <mesh name="Cilindro_72__0" geometry={nodes.Cilindro_72__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_73" position={[140.461, -116.649, 15.059]} rotation={[-2.308, -1.39, -0.587]} scale={[1, 0.754, 1]}>
            <mesh name="Cilindro_73__0" geometry={nodes.Cilindro_73__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_74" position={[142.677, -152.978, -24.093]} rotation={[-1.11, -0.886, -0.195]} scale={[1, 0.43, 1]}>
            <mesh name="Cilindro_74__0" geometry={nodes.Cilindro_74__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_75" position={[96.682, -33.499, -111.857]} rotation={[-0.216, -0.73, -1.199]} scale={[1, 0.744, 1]}>
            <mesh name="Cilindro_75__0" geometry={nodes.Cilindro_75__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_76" position={[96.487, -99.138, -105.121]} rotation={[-0.451, -0.509, 0.903]} scale={[1, 0.751, 1]}>
            <mesh name="Cilindro_76__0" geometry={nodes.Cilindro_76__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_77" position={[20.849, -89.367, -141.238]} rotation={[-0.46, 0.013, -0.834]} scale={[1, 0.326, 1]}>
            <mesh name="Cilindro_77__0" geometry={nodes.Cilindro_77__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_78" position={[37.916, -117.626, -109.468]} rotation={[-1.034, -0.088, 1.061]} scale={[1, 0.474, 1]}>
            <mesh name="Cilindro_78__0" geometry={nodes.Cilindro_78__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_79" position={[62.09, -98.102, -119.472]} rotation={[-0.736, -0.262, -2.746]} scale={[1, 0.458, 1]}>
            <mesh name="Cilindro_79__0" geometry={nodes.Cilindro_79__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_80" position={[113.555, -127.397, -73.351]} rotation={[-0.856, -0.246, 1.257]} scale={[1, 0.373, 1]}>
            <group name="Cilindro_80_2">
              <mesh name="Cilindro_80_2__0" geometry={nodes.Cilindro_80_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_81" position={[108.28, -151.942, -38.445]} rotation={[-1.145, 0.102, 0.486]} scale={[1, 0.627, 1]}>
            <group name="Cilindro_81_2">
              <mesh name="Cilindro_81_2__0" geometry={nodes.Cilindro_81_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_82" position={[-45.373, -111.772, -108.55]} rotation={[-0.918, 0.267, -1.145]} scale={[1, 0.479, 1]}>
            <group name="Cilindro_82_2">
              <mesh name="Cilindro_82_2__0" geometry={nodes.Cilindro_82_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_83" position={[-4.132, -120.507, -86.784]} rotation={[-1.422, 0.071, 1.571]} scale={[1, 0.835, 1]}>
            <mesh name="Cilindro_83__0" geometry={nodes.Cilindro_83__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_84" position={[-106.481, -145.555, -19.301]} rotation={[-1.024, 0.408, -0.277]} scale={[1, 0.758, 1]}>
            <group name="Cilindro_84_2">
              <mesh name="Cilindro_84_2__0" geometry={nodes.Cilindro_84_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_85" position={[-42.35, -120.481, -21.461]} rotation={[-1.384, -0.138, -2.526]} scale={[1, 0.788, 1]}>
            <mesh name="Cilindro_85__0" geometry={nodes.Cilindro_85__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_86" position={[40.94, -126.336, -22.379]} rotation={[-1.428, 0.239, 2.595]} scale={[1, 0.757, 1]}>
            <mesh name="Cilindro_86__0" geometry={nodes.Cilindro_86__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_87" position={[-61.324, -68.247, -123.317]} rotation={[-0.323, 0.338, -2.101]} scale={[1, 0.713, 1]}>
            <group name="Cilindro_87_2">
              <mesh name="Cilindro_87_2__0" geometry={nodes.Cilindro_87_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_88" position={[-103.372, -71.128, -100.634]} rotation={[-0.702, 0.812, 0.497]} scale={[1, 0.487, 1]}>
            <mesh name="Cilindro_88__0" geometry={nodes.Cilindro_88__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_89" position={[-159.077, -15.955, -95.783]} rotation={[-0.489, 0.521, -1.594]} scale={[1, 0.458, 1]}>
            <group name="Cilindro_89_2">
              <mesh name="Cilindro_89_2__0" geometry={nodes.Cilindro_89_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_90" position={[-162.678, -22.53, -56.144]} rotation={[-1.917, 0.585, 1.287]} scale={[1, 0.452, 1]}>
            <mesh name="Cilindro_90__0" geometry={nodes.Cilindro_90__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_91" position={[-122.923, -34.177, -75.763]} rotation={[-1.321, 0.759, 3.018]} scale={[1, 0.403, 1]}>
            <group name="Cilindro_91_2">
              <mesh name="Cilindro_91_2__0" geometry={nodes.Cilindro_91_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_92" position={[-106.972, -77.702, -60.995]} rotation={[-0.877, 1.155, 1.478]} scale={[1, 0.486, 1]}>
            <group name="Cilindro_92_2">
              <mesh name="Cilindro_92_2__0" geometry={nodes.Cilindro_92_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_93" position={[-126.033, -108.605, 5.57]} rotation={[-0.563, 1.092, 0.013]} scale={[1, 0.796, 1]}>
            <group name="Cilindro_93_2">
              <mesh name="Cilindro_93_2__0" geometry={nodes.Cilindro_93_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_94" position={[-132.335, -10.982, -21.777]} rotation={[-2.202, 1.213, 2.624]} scale={[1, 0.336, 1]}>
            <mesh name="Cilindro_94__0" geometry={nodes.Cilindro_94__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_95" position={[-187.137, -38.945, 73.131]} rotation={[-1.643, 1.115, 1.673]} scale={[1, 0.541, 1]}>
            <group name="Cilindro_95_2">
              <mesh name="Cilindro_95_2__0" geometry={nodes.Cilindro_95_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_96" position={[-150.781, -34.387, 31.84]} rotation={[-0.329, 1.006, 2.783]} scale={[1, 0.673, 1]}>
            <mesh name="Cilindro_96__0" geometry={nodes.Cilindro_96__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_97" position={[-144.97, -64.156, 17.493]} rotation={[-0.362, 1.156, 2.3]} scale={[1, 0.613, 1]}>
            <mesh name="Cilindro_97__0" geometry={nodes.Cilindro_97__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_98" position={[-144.479, -132.01, 59.186]} rotation={[-1.786, 1.137, 2.009]} scale={[1, 0.498, 1]}>
            <group name="Cilindro_98_2">
              <mesh name="Cilindro_98_2__0" geometry={nodes.Cilindro_98_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_99" position={[-145.908, -11.837, 124.068]} rotation={[-2.524, 0.678, 1.442]} scale={[1, 0.841, 1]}>
            <mesh name="Cilindro_99__0" geometry={nodes.Cilindro_99__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_100" position={[-122.188, -60.453, 122.046]} rotation={[-2.715, 0.706, -2.272]} scale={[1, 0.709, 1]}>
            <mesh name="Cilindro_100__0" geometry={nodes.Cilindro_100__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_101" position={[-59.231, -77.975, 164.26]} rotation={[-2.857, 0.188, 2.687]} scale={[1, 0.504, 1]}>
            <mesh name="Cilindro_101__0" geometry={nodes.Cilindro_101__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_102" position={[-95.188, -79.438, 139.954]} rotation={[-2.702, 0.626, 0.305]} scale={[1, 0.585, 1]}>
            <mesh name="Cilindro_102__0" geometry={nodes.Cilindro_102__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_103" position={[-136.418, -106.545, 89.017]} rotation={[-2.612, 0.748, -1.374]} scale={[1, 0.376, 1]}>
            <mesh name="Cilindro_103__0" geometry={nodes.Cilindro_103__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_104" position={[-46.703, -11.582, 170.092]} rotation={[-3.092, -0.115, 1.011]} scale={[1, 0.407, 1]}>
            <mesh name="Cilindro_104__0" geometry={nodes.Cilindro_104__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_105" position={[-24.975, -56.212, 161.369]} rotation={[-2.966, -0.438, -2.936]} scale={[1, 0.678, 1]}>
            <mesh name="Cilindro_105__0" geometry={nodes.Cilindro_105__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_106" position={[-109.494, -0.503, 174.531]} rotation={[-2.809, 0.314, 2.381]} scale={[1, 0.435, 1]}>
            <mesh name="Cilindro_106__0" geometry={nodes.Cilindro_106__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_107" position={[-75.239, 21.26, 171.641]} rotation={[-2.831, -0.013, 1.758]} scale={[1, 0.639, 1]}>
            <mesh name="Cilindro_107__0" geometry={nodes.Cilindro_107__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_108" position={[-1.078, 44.522, 193.32]} rotation={[-2.439, -0.195, -2.879]} scale={[1, 0.446, 1]}>
            <group name="Cilindro_108_2">
              <mesh name="Cilindro_108_2__0" geometry={nodes.Cilindro_108_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_109" position={[74.383, -22.677, 104.182]} rotation={[-2.937, -0.246, 0.668]} scale={[1, 0.685, 1]}>
            <mesh name="Cilindro_109__0" geometry={nodes.Cilindro_109__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_110" position={[10.395, -33.648, 135.281]} rotation={[-2.803, -0.598, 2.653]} scale={[1, 0.588, 1]}>
            <mesh name="Cilindro_110__0" geometry={nodes.Cilindro_110__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_111" position={[51.541, 21.151, 136.103]} rotation={[-2.547, -0.463, 1.687]} scale={[1, 0.72, 1]}>
            <mesh name="Cilindro_111__0" geometry={nodes.Cilindro_111__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_112" position={[13.526, 64.476, -163.067]} rotation={[0.016, 0.658, -0.277]} scale={[1, 0.387, 1]}>
            <mesh name="Cilindro_112__0" geometry={nodes.Cilindro_112__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_113" position={[38.332, 69.275, -172.305]} rotation={[-0.12, 0.292, 2.471]} scale={[1, 0.557, 1]}>
            <mesh name="Cilindro_113__0" geometry={nodes.Cilindro_113__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_114" position={[0.918, -40.867, -144.206]} rotation={[-0.172, 0.256, -0.063]} scale={[1, 0.694, 1]}>
            <mesh name="Cilindro_114__0" geometry={nodes.Cilindro_114__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_115" position={[25.092, -21.343, -154.211]} rotation={[-0.167, 0.252, -2.739]} scale={[1, 0.525, 1]}>
            <group name="Cilindro_115_2">
              <mesh name="Cilindro_115_2__0" geometry={nodes.Cilindro_115_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_116" position={[58.263, 20.775, -169.337]} rotation={[-0.235, -0.261, 2.994]} scale={[1, 0.934, 1]}>
            <group name="Cilindro_116_2">
              <mesh name="Cilindro_116_2__0" geometry={nodes.Cilindro_116_2__0.geometry} material={materials['Scene_-_Root']} />
            </group>
          </group>
          <group name="Cilindro_117" position={[-6.776, 47.442, -136.115]} rotation={[0.426, 0.735, 0.535]} scale={[1, 0.316, 1]}>
            <mesh name="Cilindro_117__0" geometry={nodes.Cilindro_117__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_118" position={[-69.018, 20.062, -115.226]} rotation={[0.482, 0.411, 2.228]} scale={[1, 0.693, 1]}>
            <mesh name="Cilindro_118__0" geometry={nodes.Cilindro_118__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Cilindro_119" position={[-57.081, -0.223, -136.29]} rotation={[0.19, 0.391, 1.899]} scale={[1, 0.711, 1]}>
            <mesh name="Cilindro_119__0" geometry={nodes.Cilindro_119__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
        <group name="Clona" scale={0.01}>
          <group name="Sfera_0" position={[10.292, 78.863, 219.438]} scale={1.251}>
            <mesh name="Sfera_0__0" geometry={nodes.Sfera_0__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_1" position={[-37.503, -122.605, 155.537]} scale={1.641}>
            <mesh name="Sfera_1__0" geometry={nodes.Sfera_1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_2" position={[159.172, -45.006, 102.977]} scale={1.999}>
            <mesh name="Sfera_2__0" geometry={nodes.Sfera_2__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_3" position={[148.341, 2.844, -72.472]} scale={1.854}>
            <mesh name="Sfera_3__0" geometry={nodes.Sfera_3__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_4" position={[21.891, 101.795, -168.954]} scale={1.872}>
            <mesh name="Sfera_4__0" geometry={nodes.Sfera_4__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_5" position={[-3.325, -108.891, -131.233]} scale={1.563}>
            <mesh name="Sfera_5__0" geometry={nodes.Sfera_5__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_6" position={[-198.832, -4.308, -76.165]} scale={1.492}>
            <mesh name="Sfera_6__0" geometry={nodes.Sfera_6__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_7" position={[-210.857, 9.67, 75.154]} scale={1.724}>
            <mesh name="Sfera_7__0" geometry={nodes.Sfera_7__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_8" position={[127.735, 162.608, 48.548]} scale={1.867}>
            <mesh name="Sfera_8__0" geometry={nodes.Sfera_8__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_9" position={[-75.692, 163.583, 26.881]} scale={2.216}>
            <mesh name="Sfera_9__0" geometry={nodes.Sfera_9__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_10" position={[-125.541, -176.458, 47.264]} scale={1.601}>
            <mesh name="Sfera_10__0" geometry={nodes.Sfera_10__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_11" position={[137.402, -177.522, 10.813]} scale={1.743}>
            <mesh name="Sfera_11__0" geometry={nodes.Sfera_11__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_12" position={[-10.641, 125.424, 25.649]} scale={1.48}>
            <mesh name="Sfera_12__0" geometry={nodes.Sfera_12__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_13" position={[65.568, 77.391, 96.837]} scale={1.931}>
            <mesh name="Sfera_13__0" geometry={nodes.Sfera_13__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_14" position={[-56.557, 145.296, 45.249]} scale={1.036}>
            <mesh name="Sfera_14__0" geometry={nodes.Sfera_14__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_15" position={[142.954, 85.246, 6.334]} scale={1.938}>
            <mesh name="Sfera_15__0" geometry={nodes.Sfera_15__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_16" position={[115.529, 32.121, 105.004]} scale={2.154}>
            <mesh name="Sfera_16__0" geometry={nodes.Sfera_16__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_17" position={[128.634, 125.951, -99.125]} scale={1.579}>
            <mesh name="Sfera_17__0" geometry={nodes.Sfera_17__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_18" position={[168.91, 22.136, 24.152]} scale={1.431}>
            <mesh name="Sfera_18__0" geometry={nodes.Sfera_18__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_19" position={[85.058, 134.063, -41.346]} scale={1.603}>
            <mesh name="Sfera_19__0" geometry={nodes.Sfera_19__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_20" position={[71.503, 111.393, -187.431]} scale={1.106}>
            <mesh name="Sfera_20__0" geometry={nodes.Sfera_20__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_21" position={[-50.244, 178.803, -99.166]} scale={2.026}>
            <mesh name="Sfera_21__0" geometry={nodes.Sfera_21__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_22" position={[-170.969, 65.378, -97.199]} scale={1.284}>
            <mesh name="Sfera_22__0" geometry={nodes.Sfera_22__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_23" position={[-18.713, 67.727, -115.051]} scale={1.11}>
            <mesh name="Sfera_23__0" geometry={nodes.Sfera_23__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_24" position={[-96.09, 53.741, 62.789]} scale={1.623}>
            <mesh name="Sfera_24__0" geometry={nodes.Sfera_24__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_25" position={[-138.146, 18.787, -7.43]} scale={1.369}>
            <mesh name="Sfera_25__0" geometry={nodes.Sfera_25__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_26" position={[-138.031, 32.339, 176.08]} scale={2.157}>
            <mesh name="Sfera_26__0" geometry={nodes.Sfera_26__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_27" position={[2.721, -126.31, 42.944]} scale={2.077}>
            <mesh name="Sfera_27__0" geometry={nodes.Sfera_27__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_28" position={[-109.418, -125.53, 106.926]} scale={1.566}>
            <mesh name="Sfera_28__0" geometry={nodes.Sfera_28__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_29" position={[97.914, -164.319, 78.095]} scale={1.566}>
            <mesh name="Sfera_29__0" geometry={nodes.Sfera_29__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_30" position={[132.97, -104.864, 89.116]} scale={1.195}>
            <mesh name="Sfera_30__0" geometry={nodes.Sfera_30__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_31" position={[33.238, -77.476, 103.361]} scale={2.131}>
            <mesh name="Sfera_31__0" geometry={nodes.Sfera_31__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_32" position={[147.951, -128.433, -58.999]} scale={1.359}>
            <mesh name="Sfera_32__0" geometry={nodes.Sfera_32__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_33" position={[45.023, -69.843, -151.242]} scale={1.386}>
            <mesh name="Sfera_33__0" geometry={nodes.Sfera_33__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_34" position={[79.158, -126.361, -87.702]} scale={2.071}>
            <mesh name="Sfera_34__0" geometry={nodes.Sfera_34__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_35" position={[-87.421, -114.653, -85.866]} scale={1.204}>
            <mesh name="Sfera_35__0" geometry={nodes.Sfera_35__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_36" position={[-119.322, -27.603, -115.402]} scale={1.052}>
            <mesh name="Sfera_36__0" geometry={nodes.Sfera_36__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_37" position={[-126.524, -40.751, -36.124]} scale={2.212}>
            <mesh name="Sfera_37__0" geometry={nodes.Sfera_37__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_38" position={[-163.417, -87.561, 71.109]} scale={1.835}>
            <mesh name="Sfera_38__0" geometry={nodes.Sfera_38__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_39" position={[-80.958, -33.345, 172.982]} scale={1.367}>
            <mesh name="Sfera_39__0" geometry={nodes.Sfera_39__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_40" position={[-12.447, 10.181, 167.201]} scale={1.458}>
            <mesh name="Sfera_40__0" geometry={nodes.Sfera_40__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group name="Sfera_41" position={[5.161, 27.157, -157.179]} scale={1.4}>
            <mesh name="Sfera_41__0" geometry={nodes.Sfera_41__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/digital-solutions/network/scene-transformed.glb')
