/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 apartment.gltf -t -T -k -K s 
Files: apartment.gltf [40.57KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\apartment\apartment-transformed.glb [1.72MB] (-4145%)
Author: zigurat architecture studio (https://sketchfab.com/ziguratarchitecturestudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-tower-office-apartment-house-home-efbb749fb03e4fb39354c6a3895d89d7
Title: modern tower office apartment house home
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'



type GLTFResult = GLTF & {
  nodes: {
    Box020_Ceramic_0: THREE.Mesh
    ['Box026_12_-_Car_Paint_0']: THREE.Mesh
    Box028_Wall_Paint_0: THREE.Mesh
    ['Box029_03_-_Default_0']: THREE.Mesh
    ['Line001_06_-_Default_0']: THREE.Mesh
    ['Line002_04_-_Default_0']: THREE.Mesh
    ['Line004_16_-_Matte_Plastic_0']: THREE.Mesh
    ['Line005_05_-_Default_0']: THREE.Mesh
    ['Line012_11_-_Default_0']: THREE.Mesh
    ['Box042_02_-_Default_0']: THREE.Mesh
    ['Box068_15_-_Glossy_Plastic_0']: THREE.Mesh
    ['Shape021_01_-_Default_0']: THREE.Mesh
    ['Line033_24_-_Default_0']: THREE.Mesh
    ['Box069_23_-_Default_0']: THREE.Mesh
    ['Line034_22_-_Default_0']: THREE.Mesh
    ['Rectangle001_21_-_Default_0']: THREE.Mesh
    ['Rectangle002_20_-_Polished_Aluminum_0']: THREE.Mesh
  }
  materials: {
    Ceramic: THREE.MeshStandardMaterial
    ['12_-_Car_Paint']: THREE.MeshStandardMaterial
    Wall_Paint: THREE.MeshStandardMaterial
    ['03_-_Default']: THREE.MeshStandardMaterial
    ['06_-_Default']: THREE.MeshStandardMaterial
    ['04_-_Default']: THREE.MeshStandardMaterial
    ['16_-_Matte_Plastic']: THREE.MeshStandardMaterial
    ['05_-_Default']: THREE.MeshStandardMaterial
    ['11_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
    ['15_-_Glossy_Plastic']: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshStandardMaterial
    ['24_-_Default']: THREE.MeshStandardMaterial
    ['23_-_Default']: THREE.MeshStandardMaterial
    ['22_-_Default']: THREE.MeshStandardMaterial
    ['21_-_Default']: THREE.MeshStandardMaterial
    ['20_-_Polished_Aluminum']: THREE.MeshStandardMaterial
  }
}

export default function Apartment(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/apartment/apartment.gltf') as GLTFResult;

  const group = useRef<THREE.Group>(null);
  const radius =6;
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    if (group.current) {  // Ensure that group.current is defined
      group.current.position.x = radius * Math.sin(elapsedTime);
      // group.current.position.y = radius * Math.sin(elapsedTime);
      group.current.position.z = radius * Math.cos(elapsedTime);
    }
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[-55,-35,9]}>
        <mesh name="Box020_Ceramic_0" geometry={nodes.Box020_Ceramic_0.geometry} material={materials.Ceramic} position={[7.949, 20.707, -1.512]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Box026_12_-_Car_Paint_0" geometry={nodes['Box026_12_-_Car_Paint_0'].geometry} material={materials['12_-_Car_Paint']} position={[0.782, 0, -13.053]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.01} />
        <mesh name="Box028_Wall_Paint_0" geometry={nodes.Box028_Wall_Paint_0.geometry} material={materials.Wall_Paint} position={[0.596, 20.707, -4.094]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Box029_03_-_Default_0" geometry={nodes['Box029_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-7.566, 23.406, -7.929]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Line001_06_-_Default_0" geometry={nodes['Line001_06_-_Default_0'].geometry} material={materials['06_-_Default']} position={[-10.075, 16.26, -6.499]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Line002_04_-_Default_0" geometry={nodes['Line002_04_-_Default_0'].geometry} material={materials['04_-_Default']} position={[-10.075, 24.563, -6.386]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Line004_16_-_Matte_Plastic_0" geometry={nodes['Line004_16_-_Matte_Plastic_0'].geometry} material={materials['16_-_Matte_Plastic']} position={[6.038, 20.398, -2.877]} scale={0.01} />
        <mesh name="Line005_05_-_Default_0" geometry={nodes['Line005_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[-10.013, 11.375, -8.725]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Line012_11_-_Default_0" geometry={nodes['Line012_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-7.504, 24.514, -1.327]} scale={0.01} />
        <mesh name="Box042_02_-_Default_0" geometry={nodes['Box042_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0.538, 24.748, -3.824]} scale={0.01} />
        <mesh name="Box068_15_-_Glossy_Plastic_0" geometry={nodes['Box068_15_-_Glossy_Plastic_0'].geometry} material={materials['15_-_Glossy_Plastic']} position={[11.686, 3.756, -6.416]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Shape021_01_-_Default_0" geometry={nodes['Shape021_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-7.634, 2.092, -4.625]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
        <mesh name="Line033_24_-_Default_0" geometry={nodes['Line033_24_-_Default_0'].geometry} material={materials['24_-_Default']} position={[-16.676, 2.052, -6.386]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.01, 0.01, 0.01]} />
        <mesh name="Box069_23_-_Default_0" geometry={nodes['Box069_23_-_Default_0'].geometry} material={materials['23_-_Default']} position={[-15.755, -2.125, -7.894]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Line034_22_-_Default_0" geometry={nodes['Line034_22_-_Default_0'].geometry} material={materials['22_-_Default']} position={[-15.794, 0.258, -4.112]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Rectangle001_21_-_Default_0" geometry={nodes['Rectangle001_21_-_Default_0'].geometry} material={materials['21_-_Default']} position={[-15.099, 0.19, -9.101]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
        <mesh name="Rectangle002_20_-_Polished_Aluminum_0" geometry={nodes['Rectangle002_20_-_Polished_Aluminum_0'].geometry} material={materials['20_-_Polished_Aluminum']} position={[-15.755, 0.148, -7.894]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/apartment/apartment-transformed.glb')
