/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 DollarSign.gltf -t -T -k -K s 
Files: DollarSign.gltf [6.9KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\dollar-sign\DollarSign-transformed.glb [29.67KB] (-330%)
Author: Akimix (https://sketchfab.com/Akimix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dollar-7e8f93b656b742128c4601bf87c6bc07
Title: DOLLAR
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Action' | 'dollerAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function DolarSign(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/dollar-sign/DollarSign-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="doller_0" position={[0.045, 0.058, 0.032]} rotation={[Math.PI / 2, 0, 0]} scale={[3.776, 4.934, 3.776]}>
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/dollar-sign/DollarSign-transformed.glb')
