/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 X.gltf -k -K -t -T s 
Files: X.gltf [5.49KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\x\X-transformed.glb [61.48KB] (-1020%)
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-twitter-x-logo-814e35fbc3e543ac91ca959355f251c0
Title: 3D Twitter X Logo
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    github: THREE.MeshStandardMaterial
    glossy_putih: THREE.MeshStandardMaterial
  }
}

export default function XIcon(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/x/X-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.github} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.glossy_putih} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/x/X-transformed.glb')
