/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 SocialMediaIconsAll.gltf -k -K -t -T s 
Files: SocialMediaIconsAll.gltf [364.62KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\social-media-icons-pro\all\SocialMediaIconsAll-transformed.glb [172.75KB] (53%)
Author: Daniel.Riches (https://sketchfab.com/Daniel.Riches)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/social-media-icons-60aab1d19fe24b6e9bad815bbdcbc24d
Title: Social Media Icons
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    AndroidLogo_AndroidLogo002_0: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

export default function SocialMediaIconsPro(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/social-media-icons-pro/all/SocialMediaIconsAll-transformed.glb') as GLTFResult

  console.log(nodes, materials);
  
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="AndroidLogo_AndroidLogo002_0" geometry={nodes.AndroidLogo_AndroidLogo002_0.geometry} material={materials.PaletteMaterial001} position={[-5.528, 0.1, -1.428]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/social-media-icons-pro/all/SocialMediaIconsAll-transformed.glb')
