/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 SmilingEmojiOne.gltf -t -T -k -K s 
Files: SmilingEmojiOne.gltf [19.64KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\emoji-smile-one\SmilingEmojiOne-transformed.glb [71.94KB] (-266%)
Author: JadeBarbiier (https://sketchfab.com/JadeBarbiier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emoji-smile-04-b5cd533da2a340429b10e6391d129a3d
Title: Emoji_Smile_04
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { JoinGrowthProps } from '@/library/types/common'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    ['0']: THREE.Mesh
    ['1']: THREE.Mesh
    ['2']: THREE.Mesh
    ['3']: THREE.Mesh
  }
  materials: {
    Brown1: THREE.MeshStandardMaterial
    Teeth: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Mouth: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const SmilingEmojiOne: React.FC<JoinGrowthProps> = ({ animate, ...props }) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/3d-objects/emoji-smile-one/SmilingEmojiOne-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="group1" position={[0, -35.495, 0]}>
            <group name="Smile_02" position={[0.005, 35.495, 0]}>
              <mesh name="0" geometry={nodes['0'].geometry} material={materials.Brown1} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
              <mesh name="1" geometry={nodes['1'].geometry} material={materials.Teeth} morphTargetDictionary={nodes['1'].morphTargetDictionary} morphTargetInfluences={nodes['1'].morphTargetInfluences} />
              <mesh name="2" geometry={nodes['2'].geometry} material={materials.Skin} morphTargetDictionary={nodes['2'].morphTargetDictionary} morphTargetInfluences={nodes['2'].morphTargetInfluences} />
              <mesh name="3" geometry={nodes['3'].geometry} material={materials.Mouth} morphTargetDictionary={nodes['3'].morphTargetDictionary} morphTargetInfluences={nodes['3'].morphTargetInfluences} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/emoji-smile-one/SmilingEmojiOne-transformed.glb')
export default SmilingEmojiOne
