/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 LinkedIn.gltf -k -K -t -T s 
Files: LinkedIn.gltf [5.5KB] > C:\Users\owner\Desktop\maliek_davis\public\3d-objects\icons\linkedin\LinkedIn-transformed.glb [68.55KB] (-1146%)
Author: pengedarseni (https://sketchfab.com/pengedarseni)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-linkedin-logo-e8786a94c6a942c594696d58d8c59a50
Title: 3D Linkedin Logo
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    glossy_linkedin: THREE.MeshStandardMaterial
    glossy_putih: THREE.MeshStandardMaterial
  }
}

export default function LinkedIn(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-objects/icons/linkedin/LinkedIn-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.glossy_linkedin} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.glossy_putih} position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d-objects/icons/linkedin/LinkedIn-transformed.glb')
